### ISSUE TITLE
TypeError in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1554] opened 2019-10-17 06:21 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 't.fields[o]')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5da80851f9b4bd00194434d5?event_id=5da8085100511b40b40f0000&i=gh&m=ci)

## Stacktrace

    app/helpers/utils.js:62 - updateFormSchema
    app/helpers/utils.js:45 - errorReturn
    app/containers/RegisterTrees/index.js:51 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5da80851f9b4bd00194434d5?event_id=5da8085100511b40b40f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-10-26 11:14
Duplicate of #1041

**Closed by norbertschuler** 2019-10-26 11:14 UTC
Labels: 1.1.0, bug, bugsnag, production
