### ISSUE TITLE
java.lang.IllegalStateException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1349] opened 2019-08-30 03:02 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6891dd0ce6bd001a29f1ee?event_id=5d6891dd004e28bec1800000&i=gh&m=ci)

## Stacktrace

    SourceFile:90 - njj.a

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6891dd0ce6bd001a29f1ee?event_id=5d6891dd004e28bec1800000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-17 12:04
Duplicate of #1405

**Closed by norbertschuler** 2019-09-17 12:04 UTC
Labels: 1.0.6, bug, bugsnag, production
