### ISSUE TITLE
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2497] opened 2020-06-25 18:08 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef4e81313ee9e00177defd8?event_id=5ef4e813005b6f1c23f30000&i=gh&m=ci)

## Stacktrace

    DrawableContainer.java:877 - android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef4e81313ee9e00177defd8?event_id=5ef4e813005b6f1c23f30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-27 06:49
Duplicate of #1889

**Closed by norbertschuler** 2020-06-27 06:49 UTC
Labels: 1.3.4, bug, bugsnag, production
