### ISSUE TITLE
Error in /donate-trees - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2234] opened 2020-04-23 22:17 UTC
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea21402d4351c00189764f5?event_id=5ea21402005a84ce92fd0000&i=gh&m=ci)

## Stacktrace

    https://www.paypalobjects.com/api/checkout.js:5543 - cleanUpWindow

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea21402d4351c00189764f5?event_id=5ea21402005a84ce92fd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 11:43
Duplicate of #1943

**Comment by Plant-for-the-Planet** [comment] 2020-07-14 00:09
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea21402d4351c00189764f5?event_id=5f0cf78e005b769e03260000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-08-24 07:31
Duplicate of #1943

**Closed by norbertschuler** 2020-08-24 07:31 UTC
Labels: 1.3.2, bug, bugsnag, production
