### ISSUE TITLE
java.lang.RuntimeException in Binder.java:751

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1591] opened 2019-11-04 08:18 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:751**
android.os.TransactionTooLargeException: data parcel size 544220 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbfdec262b5fa001a94c697?event_id=5dbfdec2005253945be30000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4714 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbfdec262b5fa001a94c697?event_id=5dbfdec2005253945be30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:51
Duplicate of #1745

**Closed by norbertschuler** 2019-12-13 07:51 UTC
Labels: 1.1.0, bug, bugsnag, production
