### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2963] opened 2021-03-04 19:30 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60413569e65259001745c9b9?event_id=604135690072e705a6230000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:2165888 - 0x7cfa9ddc80

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60413569e65259001745c9b9?event_id=604135690072e705a6230000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:35
Duplicate of #2982

**Closed by norbertschuler** 2021-03-29 07:35 UTC
Labels: 1.4.0, bug, bugsnag, production
