### ISSUE TITLE
TypeError in /edit-trees/308707 - Cannot read property 'getValue' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2192] opened 2020-04-08 16:41 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/edit-trees/308707**
Cannot read property 'getValue' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8dfebaf448e3001826a666?event_id=5e8dfeba0059981c834f0000&i=gh&m=ci)

## Stacktrace

    app/components/EditUserContribution/index.js:92 - EditUserContribution.onSubmitClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8dfebaf448e3001826a666?event_id=5e8dfeba0059981c834f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-12 06:04
Duplicate of #2015

**Closed by norbertschuler** 2020-04-12 06:04 UTC
Labels: 1.3.2, bug, bugsnag, production
