### ISSUE TITLE
java.lang.NullPointerException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3150] opened 2022-01-19 13:29 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/61e8124ed64fcb00073bfca0?event_id=61e8124e008c5b5b3c4f0000&i=gh&m=ci)

## Stacktrace

    Editor.java:6718 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/61e8124ed64fcb00073bfca0?event_id=61e8124e008c5b5b3c4f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2022-06-08 19:10
Duplicate of #3176

**Closed by norbertschuler** 2022-06-08 19:10 UTC
Labels: bug, bugsnag, production, native, 1.4.7
