### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2978] opened 2021-03-20 18:26 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60563e6be67f810008e60bf3?event_id=60563e6b00754cbf52960000&i=gh&m=ci)

## Stacktrace

    /system/lib/libhwui.so:3028424 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60563e6be67f810008e60bf3?event_id=60563e6b00754cbf52960000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:32
Duplicate of #2979

**Closed by norbertschuler** 2021-03-29 07:32 UTC
Labels: 1.4.0, bug, bugsnag, production
