### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2938] opened 2021-01-25 08:02 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/600e7b272ccfa60017d2ea83?event_id=600e7b270069a9ac204d0000&i=gh&m=ci)

## Stacktrace

    /system/lib/libhwui.so:1789928 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/600e7b272ccfa60017d2ea83?event_id=600e7b270069a9ac204d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:33
Duplicate of #2979

**Closed by norbertschuler** 2021-03-29 07:33 UTC
Labels: 1.3.9, bug, bugsnag, native, production
