### ISSUE TITLE
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2992] opened 2021-04-10 08:55 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/607167fb649f9100073f12d6?event_id=607167fb0077351b01b20000&i=gh&m=ci)

## Stacktrace

    DrawableContainer.java:877 - android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/607167fb649f9100073f12d6?event_id=607167fb0077351b01b20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-08-06 10:34
Duplicate of #1889

**Closed by norbertschuler** 2021-08-06 10:34 UTC
Labels: bug, bugsnag, production, 1.4.0
