### ISSUE TITLE
Error in / - Unexpected input given to normalize. Expected type to be "object", found "string".

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2456] opened 2020-06-11 13:38 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee233b88bb720001776bcca?event_id=5ee233b8005b7118f0a70000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.8aff6290fd07f2539028.js:1 - normalize

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee233b88bb720001776bcca?event_id=5ee233b8005b7118f0a70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 13:32
Duplicate of #2329

**Closed by norbertschuler** 2020-06-22 13:32 UTC
Labels: 1.3.4, bug, bugsnag, production
