### ISSUE TITLE
java.lang.NullPointerException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3127] opened 2021-10-30 21:38 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/617dbb4af216e70007ac0047?event_id=617dbb4a0089784d37580000&i=gh&m=ci)

## Stacktrace

    DrawableContainer.java:883 - android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/617dbb4af216e70007ac0047?event_id=617dbb4a0089784d37580000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2022-06-08 19:22
Duplicate of #3158

**Closed by norbertschuler** 2022-06-08 19:22 UTC
Labels: bug, bugsnag, production, native, 1.4.6
