### ISSUE TITLE
java.lang.NullPointerException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2945] opened 2021-02-11 19:12 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/602581a2c87e2a00175a5e88?event_id=602581a200699affcd9f0000&i=gh&m=ci)

## Stacktrace

    Editor.java:6752 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/602581a2c87e2a00175a5e88?event_id=602581a200699affcd9f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:44
Duplicate of #2219

**Closed by norbertschuler** 2021-03-29 07:44 UTC
Labels: 1.3.9, bug, bugsnag, production
