### ISSUE TITLE
Challenge navigation issue from left side menu

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1605] opened 2019-11-08 00:55 UTC
**Describe the bug**
Develop branch challenge menu item missing it nav props, can not go right way.

**Is it on a Production or Development Build?**
Development 

**To Reproduce**
1. Go to https://staging.trilliontreecampaign.org/app_challenge
2. Click on Challenge left side menu item

**Expected behavior**
Soould come up the challenge page.

**What actually happens**
404

**Screenshots**
![Screenshot from 2019-11-08 06-49-27](https://user-images.githubusercontent.com/2967789/68440394-1807c880-01f5-11ea-8269-ae01f80704bf.png)

**Desktop (please complete the following information):**
- OS: linux
 - Browser  chrome

**Comment by mahmed0715** [comment] 2019-11-08 00:58
![Screenshot from 2019-11-08 06-58-26](https://user-images.githubusercontent.com/2967789/68440420-3241a680-01f5-11ea-836a-f6e9de6b9e3d.png)

**Comment by mahmed0715** [comment] 2019-11-08 00:59
looks like backend issue @jmiridis

**Comment by norbertschuler** [comment] 2019-11-12 05:26
Duplicate of #1617

**Closed by norbertschuler** 2019-11-12 05:26 UTC
Labels: Web, bug, client
