### ISSUE TITLE
Missing profile image in treecounter

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2025] opened 2020-03-04 10:32 UTC
**Describe the bug**
Loading a treecounter e.g. https://www.trilliontreecampaign.org/t/norbert-schuler shows a missing image when reloading the page and the image request returns with an 404 error trying to load https://www.trilliontreecampaign.org/t/undefined/profile/thumb/5d50ee2c6125d619106659.jpeg 

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to a treecounter
2. Reload the page
3. See error

**Expected behavior**
Use the right url to load the profile image.

**What actually happens**
The link for loading the profile image is not correct and therefore the image can not be loaded.

**Screenshots**
<img width="1680" alt="Bildschirmfoto 2020-03-04 um 11 31 10" src="https://user-images.githubusercontent.com/1532418/75870708-ab4fb400-5e0b-11ea-9806-9fdcc69cd6d3.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome
- Plant-for-the-Planet App Version 1.3.1

**Comment by norbertschuler** [comment] 2020-03-04 10:38
Normally this page loads with `https://cdn-app.plant-for-the-planet.org/media/cache/profile/thumb/5d50ee2c6125d619106659.jpeg` for the profile image:

<img width="1680" alt="Bildschirmfoto 2020-03-04 um 11 35 54" src="https://user-images.githubusercontent.com/1532418/75871265-9293ce00-5e0c-11ea-80a4-03604b95e07d.png">

but when I click reload in the browser the page tries to load the image from `undefined/profile/thumb/5d50ee2c6125d619106659.jpeg` like this:

<img width="1678" alt="Bildschirmfoto 2020-03-04 um 11 36 18" src="https://user-images.githubusercontent.com/1532418/75871218-8445b200-5e0c-11ea-9609-a7425c6c5a9f.png">

**Comment by haideralishah** [comment] 2020-03-16 11:53
@norbertschuler
I Check this on Production it is working fine on my side I have tried so many times with Mac and ubuntu chrome.
check this now if it's working Ok please close this issue.

**Comment by haideralishah** [comment] 2020-03-17 13:03
The issue is no more is the latest production build so I m closing this issue.

**Closed by haideralishah** 2020-03-17 13:03 UTC
Labels: Web, bug
