### ISSUE TITLE
TypeError in /gift-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1497] opened 2019-09-30 09:26 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
Cannot read property 'contribution' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d91ca292a22fd00187d450e?event_id=5d91ca29005033132cf80000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:158024 - CheckoutForm._this.handlePayment

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d91ca292a22fd00187d450e?event_id=5d91ca29005033132cf80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-30 09:38
Duplicate of #1413

**Closed by norbertschuler** 2019-09-30 09:38 UTC
Labels: 1.1.0, bug, bugsnag, production
