### ISSUE TITLE
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3073] opened 2021-07-29 20:04 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/610309dc59bad60007759025?event_id=610309dc007f9103e0980000&i=gh&m=ci)

## Stacktrace

    DrawableContainer.java:875 - android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/610309dc59bad60007759025?event_id=610309dc007f9103e0980000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-08-06 10:34
Duplicate of #1889

**Closed by norbertschuler** 2021-08-06 10:34 UTC
Labels: bug, bugsnag, production, 1.4.3
