### ISSUE TITLE
TypeError in /login - null is not an object (evaluating 'v.l.then')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2188] opened 2020-04-08 08:58 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
null is not an object (evaluating 'v.l.then')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8d9220e86c0900170fc7aa?event_id=5e8d92200059a2b286a80000&i=gh&m=ci)

## Stacktrace

    https://www.gstatic.com/recaptcha/releases/NjSCg_IbX1Pdc6A9cf-rvw4e/recaptcha__de.js:509 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8d9220e86c0900170fc7aa?event_id=5e8d92200059a2b286a80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment] 2020-04-08 09:00
Problem with Recaptcha


Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/login**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8d9220e86c0900170fc7aa?event_id=5e8d92200059a2b286a80000&i=gh&m=cm)

**Comment by norbertschuler** [comment] 2020-04-08 10:29
Duplicate of #2116

**Closed by norbertschuler** 2020-04-08 10:29 UTC
Labels: 1.3.2, bug, bugsnag, production
