### ISSUE TITLE
window.onerror in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1979] opened 2020-02-19 16:32 UTC
## Error in Plant-for-the-Planet App

**window.onerror** in **/**
TypeError: ht.default.notify is not a function. (In 'ht.default.notify(j,(function(j){j.metadata={info:q}}))', 'ht.default.notify' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4d6333c1e5b0001ace6fbe?event_id=5e4d63330055f5093ff70000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.209a26fd877435f44724.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4d6333c1e5b0001ace6fbe?event_id=5e4d63330055f5093ff70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-01 15:18
Duplicate of #1946

**Closed by norbertschuler** 2020-04-01 15:18 UTC
Labels: 1.3.1, bug, bugsnag, production
