### ISSUE TITLE
Hide Support in Competition (cases)

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1985] opened 2020-02-20 14:06 UTC
Hide the support button if:

- [x] the user is a participant of the competition

- [x] the competition has closed

- [x] the user is the competition owner

<img width="475" alt="Screen Shot 2020-02-20 at 3 05 01 PM" src="https://user-images.githubusercontent.com/5401575/74940983-9417cc00-53f2-11ea-8274-c1ab0fa46946.png">

**Comment by norbertschuler** [comment] 2020-05-02 05:38
@sagararyal is this a duplicate of #2264?

**Comment by harshvitra** [comment] 2020-05-02 20:42
> @sagararyal is this a duplicate of #2264? Can we close it or should we keep it?



> * [ ]  the user is the competition owner

Right now we have "Plant Trees" button as the user becomes a participant

**Closed** 2020-05-19 05:54 UTC
Labels: Fixed - Not merged, enhancement
