### ISSUE TITLE
Error in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1328] opened 2019-08-28 14:46 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 401

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6693bf9cf07b00198b85ea?event_id=5d6693bf004e317b0d730000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:37694 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6693bf9cf07b00198b85ea?event_id=5d6693bf004e317b0d730000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-28 14:52
I something get an 401 when I switch branches and backends in my client. Then the web client is just showing an empty white page and not reloading to show the login page again. I just hope that can not happen to our users.

**Comment by Plant-for-the-Planet** [comment] 2019-08-28 14:53
I sometimes get a 401 when I switch branches and backends in my client. Then the web client is ju...

Comment added in Bugsnag by Norbert Schuler
[**Error** in **/**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6693bf9cf07b00198b85ea?event_id=5d669429004e3d4f0e130000&i=gh&m=cm)

**Comment by norbertschuler** [comment] 2019-09-17 12:25
Duplicate of #1427

**Closed by norbertschuler** 2019-09-17 12:25 UTC
Labels: 1.0.5, bug, bugsnag, production
