### ISSUE TITLE
com.facebook.react.bridge.JSApplicationIllegalArgumentException in ReadableNativeMap.java:109 - Error while updating property 'coordinate' of a view managed by: AIRMapMarker

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1956] opened 2020-02-15 14:07 UTC
## Error in Plant-for-the-Planet App

**com.facebook.react.bridge.JSApplicationIllegalArgumentException** in **ReadableNativeMap.java:109**
Error while updating property 'coordinate' of a view managed by: AIRMapMarker

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e47fb3df1affa001aec1295?event_id=5e47fb3d0055f25e165f0000&i=gh&m=ci)

## Stacktrace

```java
com.facebook.react.bridge.JSApplicationIllegalArgumentException Error while updating property 'coordinate' of a view managed by: AIRMapMarker 
    ViewManagersPropertyCache.java:98 com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
    ViewManagerPropertyUpdater.java:134 com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty
    ViewManagerPropertyUpdater.java:54 com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps
    ViewManager.java:48 com.facebook.react.uimanager.ViewManager.updateProperties
    NativeViewHierarchyManager.java:278 com.facebook.react.uimanager.NativeViewHierarchyManager.createView
    UIViewOperationQueue.java:179 com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute
    UIViewOperationQueue.java:972 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:943 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:28 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:174 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:84 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:924 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:735 android.view.Choreographer.doCallbacks
    Choreographer.java:664 android.view.Choreographer.doFrame
    Choreographer.java:912 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:761 android.os.Handler.handleCallback
    Handler.java:98 android.os.Handler.dispatchMessage
    Looper.java:156 android.os.Looper.loop
    ActivityThread.java:6517 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:942 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:832 com.android.internal.os.ZygoteInit.main

Caused by: java.lang.reflect.InvocationTargetException
    Method.java:-2 java.lang.reflect.Method.invoke
    ViewManagersPropertyCache.java:83 com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
    ViewManagerPropertyUpdater.java:134 com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty
    ViewManagerPropertyUpdater.java:54 com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps
    ViewManager.java:48 com.facebook.react.uimanager.ViewManager.updateProperties
    NativeViewHierarchyManager.java:278 com.facebook.react.uimanager.NativeViewHierarchyManager.createView
    UIViewOperationQueue.java:179 com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute
    UIViewOperationQueue.java:972 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:943 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:28 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:174 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:84 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:924 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:735 android.view.Choreographer.doCallbacks
    Choreographer.java:664 android.view.Choreographer.doFrame
    Choreographer.java:912 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:761 android.os.Handler.handleCallback
    Handler.java:98 android.os.Handler.dispatchMessage
    Looper.java:156 android.os.Looper.loop
    ActivityThread.java:6517 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:942 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:832 com.android.internal.os.ZygoteInit.main

Caused by: com.facebook.react.bridge.NoSuchKeyException latitude 
    ReadableNativeMap.java:109 com.facebook.react.bridge.ReadableNativeMap.getValue
    ReadableNativeMap.java:113 com.facebook.react.bridge.ReadableNativeMap.getValue
    ReadableNativeMap.java:150 com.facebook.react.bridge.ReadableNativeMap.getDouble
    AirMapMarker.java:159 com.airbnb.android.react.maps.AirMapMarker.setCoordinate
    AirMapMarkerManager.java:169 com.airbnb.android.react.maps.AirMapMarkerManager.setCoordinate
    Method.java:-2 java.lang.reflect.Method.invoke
    ViewManagersPropertyCache.java:83 com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
    ViewManagerPropertyUpdater.java:134 com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty
    ViewManagerPropertyUpdater.java:54 com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps
    ViewManager.java:48 com.facebook.react.uimanager.ViewManager.updateProperties
    NativeViewHierarchyManager.java:278 com.facebook.react.uimanager.NativeViewHierarchyManager.createView
    UIViewOperationQueue.java:179 com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute
    UIViewOperationQueue.java:972 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:943 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:28 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:174 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:84 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:924 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:735 android.view.Choreographer.doCallbacks
    Choreographer.java:664 android.view.Choreographer.doFrame
    Choreographer.java:912 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:761 android.os.Handler.handleCallback
    Handler.java:98 android.os.Handler.dispatchMessage
    Looper.java:156 android.os.Looper.loop
    ActivityThread.java:6517 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:942 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:832 com.android.internal.os.ZygoteInit.main

```
[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e47fb3df1affa001aec1295?event_id=5e47fb3d0055f25e165f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-05-03 11:24
do not fix native bugs yet

**Comment by Plant-for-the-Planet** [comment] 2020-05-12 15:13
An error linked to this issue has been reopened in Bugsnag
[**com.facebook.react.bridge.JSApplicationIllegalArgumentException** in **ReadableNativeMap.java:109**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e47fb3df1affa001aec1295?event_id=5ebabd0d005b3de07f420000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-09-17 14:05
Duplicate of #2718

**Closed by norbertschuler** 2020-09-17 14:05 UTC
Labels: 1.3.1, bug, bugsnag, native, production
