### ISSUE TITLE
java.lang.IllegalStateException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1152] opened 2019-07-26 17:15 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3b35336cfee5001a7bd4e5?event_id=5d3b3533004b4380c5020000&i=gh&m=ci)

## Stacktrace

    SourceFile:95 - nbk.a

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3b35336cfee5001a7bd4e5?event_id=5d3b3533004b4380c5020000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-07-31 04:32
can not fix native crash of YouTube player

**Comment by Plant-for-the-Planet** [comment] 2019-08-28 17:44
An error linked to this issue has been reopened in Bugsnag
[**java.lang.IllegalStateException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3b35336cfee5001a7bd4e5?event_id=5d66bd81004e4af584900000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2019-09-17 12:07
Duplicate of #1405

**Closed by norbertschuler** 2019-09-17 12:07 UTC
Labels: 1.0.3, bug, bugsnag, production
