### ISSUE TITLE
TypeError in /login - Cannot read property '6Ldl8WoUAAAAAGj0OIKqbvkm_XiDPbve07JJySBF' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2715] opened 2020-09-10 21:23 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
Cannot read property '6Ldl8WoUAAAAAGj0OIKqbvkm_XiDPbve07JJySBF' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f5a99436acdc30017d312fa?event_id=5f5a9943005debac22a20000&i=gh&m=ci)

## Stacktrace

    https://www.gstatic.com/recaptcha/releases/iSHzt4kCrNgSxGUYDFqaZAL9/recaptcha__en.js:170 - Array.<anonymous>

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f5a99436acdc30017d312fa?event_id=5f5a9943005debac22a20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-09-17 14:19
Duplicate of #2706

**Closed by norbertschuler** 2020-09-17 14:19 UTC
Labels: 1.3.6, bug, bugsnag, production
