### ISSUE TITLE
java.lang.RuntimeException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1592] opened 2019-11-04 11:42 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **MainActivity**
android.os.TransactionTooLargeException: data parcel size 598660 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc00eb3e6e2d4001ad1b107?event_id=5dc00eb300524a4cf5d50000&i=gh&m=ci)

## Stacktrace

    PendingTransactionActions.java:160 - android.app.servertransaction.PendingTransactionActions$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc00eb3e6e2d4001ad1b107?event_id=5dc00eb300524a4cf5d50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:58
Duplicate of #1745

**Closed by norbertschuler** 2019-12-13 07:58 UTC
Labels: 1.1.0, bug, bugsnag, production
