### ISSUE TITLE
Error in /gift-trees - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1996] opened 2020-02-24 13:54 UTC
## Error in Plant-for-the-Planet App

**Error** in **/gift-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e53d577c9368f001a28604d?event_id=5e53d5770055e72e37b70000&i=gh&m=ci)

## Stacktrace

    app/components/Payment/PaymentSelector.js:65 - decorateSuccess
    app/components/Payment/PaymentSelector.js:284 - onSuccess
    app/components/Payment/Gateways/Paypal.js:112 - onCancel
    src/button/component.jsx:805 - decorateOnCancel

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e53d577c9368f001a28604d?event_id=5e53d5770055e72e37b70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 05:31
Same as #1943

**Comment by norbertschuler** [comment] 2020-06-22 08:57
Duplicate of #1943

**Comment by Plant-for-the-Planet** [comment] 2020-09-30 16:27
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/support/youtopia**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e53d577c9368f001a28604d?event_id=5f74b1fd0060b73e5fd40000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-10-04 08:43
Related to #2725

**Closed** 2020-12-20 14:34 UTC
Labels: 1.3.1, bug, bugsnag, production
