### ISSUE TITLE
Error in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1247] opened 2019-08-15 16:37 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 404

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d558a63781e09001aa17abb?event_id=5d558a63004ccc0ae6c10000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:25 - e.exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d558a63781e09001aa17abb?event_id=5d558a63004ccc0ae6c10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-19 12:39
Duplicate of #1243

**Closed by norbertschuler** 2019-08-19 12:39 UTC
Labels: 1.0.5, bug, bugsnag, production
