### ISSUE TITLE
Error in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2496] opened 2020-06-25 04:51 UTC
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef42d53e2eaad0018c44a46?event_id=5ef42d53005b681542770000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.8aff6290fd07f2539028.js:1 - normalize

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef42d53e2eaad0018c44a46?event_id=5ef42d53005b681542770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-25 06:07
Duplicate of #2329

**Closed by norbertschuler** 2020-06-25 06:07 UTC
Labels: 1.3.4, bug, bugsnag, production
