### ISSUE TITLE
window.onerror in / - TypeError: At.default.notify is not a function. (In 'At.default.notify(E,(function(E){E.metadata={info:j}}))', 'At.default.notify' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2389] opened 2020-06-06 16:58 UTC
## Error in Plant-for-the-Planet App

**window.onerror** in **/**
TypeError: At.default.notify is not a function. (In 'At.default.notify(E,(function(E){E.metadata={info:j}}))', 'At.default.notify' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edbcb498647850017821ba5?event_id=5edbcb49005b7aadc68a0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.a773eaf50b0127ee38d7.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edbcb498647850017821ba5?event_id=5edbcb49005b7aadc68a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-07 03:57
Duplicate of #2388

**Comment by Plant-for-the-Planet** [comment] 2020-06-10 02:23
An error linked to this issue has been reopened in Bugsnag
[**window.onerror** in **/donate-trees/1**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edbcb498647850017821ba5?event_id=5ee04414005b6d23e29e0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-06-22 12:33
Duplicate of #2388

**Closed by norbertschuler** 2020-06-22 12:33 UTC
Labels: 1.3.3, bug, bugsnag, production
