### ISSUE TITLE
java.lang.IllegalStateException in MessageQueue.java:331

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2510] opened 2020-07-01 22:59 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MessageQueue.java:331**
Unable to create layer for ReactHorizontalScrollContainerView

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5efd15680e8ef500175a80ae?event_id=5efd1568005b71f3e6770000&i=gh&m=ci)

## Stacktrace

    MessageQueue.java:-2 - android.os.MessageQueue.nativePollOnce

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5efd15680e8ef500175a80ae?event_id=5efd1568005b71f3e6770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-08-24 07:28
Duplicate of #2560

**Closed by norbertschuler** 2020-08-24 07:28 UTC
Labels: 1.3.4, bug, bugsnag, native, production
