### ISSUE TITLE
TypeError in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2001] opened 2020-02-25 17:22 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Object doesn't support property or method 'notify'

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e5557d7f64d4d001aca2868?event_id=5e5557d70055e25108f50000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.60e8859637039a06d1f5.js:1 - componentDidCatch

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e5557d7f64d4d001aca2868?event_id=5e5557d70055e25108f50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 05:34
Duplicate of #1946

**Closed by norbertschuler** 2020-04-02 05:34 UTC
Labels: 1.3.1, bug, bugsnag, production
