### ISSUE TITLE
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1756] opened 2019-12-15 04:59 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/TreecounterGraphics/Trillion.native.js:194**
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df5bdc6d25e3c0019d5ee73?event_id=5df5bdc60054bb04877d0000&i=gh&m=ci)

## Stacktrace

    app/components/TreecounterGraphics/Trillion.native.js:194 - _renderScreen
    app/actions/pledgeEventsAction.js:10 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df5bdc6d25e3c0019d5ee73?event_id=5df5bdc60054bb04877d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-15 10:51
@harshvitra1412 do you have an idea, why this still throws an error on production?

**Comment by norbertschuler** [comment] 2019-12-17 08:29
Well, I can't explain this. It also only happened once, so I think we can ignore it for now.

**Comment by norbertschuler** [comment] 2020-02-04 11:21
Duplicate of #1861

**Closed by norbertschuler** 2020-02-04 11:21 UTC
Labels: 1.49.2, bug, bugsnag, production
