### ISSUE TITLE
java.lang.RuntimeException in Binder.java:750

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1978] opened 2020-02-19 15:58 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:750**
android.os.TransactionTooLargeException: data parcel size 695448 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4d5b07283ce6001b62113f?event_id=5e4d5b0700560355c9140000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4153 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4d5b07283ce6001b62113f?event_id=5e4d5b0700560355c9140000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 06:52
Duplicate of #2076

**Comment by norbertschuler** [comment] 2020-05-03 11:24
do not fix native bugs yet

**Closed by norbertschuler** 2020-05-03 11:24 UTC
Labels: 1.3.1, bug, bugsnag, native, production
