### ISSUE TITLE
Error in app/actions/treecounterLookupAction.js:33 - Unexpected input given to normalize. Expected type to be "object", found "string".

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2355] opened 2020-05-14 19:01 UTC
## Error in Plant-for-the-Planet App

**Error** in **app/actions/treecounterLookupAction.js:33**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebd95802cbd94001746bf89?event_id=5ebd9580005b393c56c60000&i=gh&m=ci)

## Stacktrace

    app/actions/treecounterLookupAction.js:33 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebd95802cbd94001746bf89?event_id=5ebd9580005b393c56c60000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 12:23
code cannot deal with unexpected result of API

**Comment by norbertschuler** [comment] 2020-06-22 13:32
Duplicate of #2329

**Closed by norbertschuler** 2020-06-22 13:32 UTC
Labels: 1.3.3, bug, bugsnag, production
