### ISSUE TITLE
Error in /gift-trees - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2624] opened 2020-08-15 13:42 UTC
## Error in Plant-for-the-Planet App

**Error** in **/gift-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f37e63eaa5c6a00170c940d?event_id=5f37e63e005b7a43dca90000&i=gh&m=ci)

## Stacktrace

    https://www.paypalobjects.com/api/checkout.js:5573 - cleanUpWindow

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f37e63eaa5c6a00170c940d?event_id=5f37e63e005b7a43dca90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-09-17 14:24
Duplicate of #2725

**Closed by norbertschuler** 2020-09-17 14:24 UTC
Labels: 1.3.5, bug, bugsnag, production
