### ISSUE TITLE
TypeError in /register-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2189] opened 2020-04-08 10:14 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/register-trees**
Cannot read property 'includes' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8da40209a1e200178acd15?event_id=5e8da4020059a4a5a4d30000&i=gh&m=ci)

## Stacktrace

    app/containers/RegisterTrees/index.js:33 - Object.onSubmit
    app/components/RegisterTrees/index.js:143 - RegisterTrees.onSubmitClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8da40209a1e200178acd15?event_id=5e8da4020059a4a5a4d30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-08 10:28
Duplicate of #1960

**Closed by norbertschuler** 2020-04-08 10:28 UTC
Labels: 1.3.2, bug, bugsnag, production
