### ISSUE TITLE
TypeError in /pledge/mandoki-soulmates

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1472] opened 2019-09-26 10:26 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/pledge/mandoki-soulmates**
Cannot read property 'map' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8c92563cacb6001b671281?event_id=5d8c925600503f31475c0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:174626 - Pledge.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8c92563cacb6001b671281?event_id=5d8c925600503f31475c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-26 13:24
Duplicate of #1463

**Closed by norbertschuler** 2019-09-26 13:24 UTC
Labels: 1.0.8, bug, bugsnag, production
