### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3001] opened 2021-04-17 07:08 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/607a897b7698b9000867276f?event_id=607a897b0077c064ded70000&i=gh&m=ci)

## Stacktrace

    Editor.java:6761 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/607a897b7698b9000867276f?event_id=607a897b0077c064ded70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-04-20 14:12
Duplicate of #3003

**Closed by norbertschuler** 2021-04-20 14:12 UTC
Labels: 1.4.0, bug, bugsnag, production
