### ISSUE TITLE
Error in /pledge/jubilaum-stephan-heinrich

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2013] opened 2020-02-28 07:40 UTC
## Error in Plant-for-the-Planet App

**Error** in **/pledge/jubilaum-stephan-heinrich**
pledgedEvent not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fb88afa900193f7dde?event_id=5e58c3fb00567866f3f10000&i=gh&m=ci)

## Stacktrace

    app/containers/Pledge/index.js:55 - componentDidUpdate

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fb88afa900193f7dde?event_id=5e58c3fb00567866f3f10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-02-28 08:09
Duplicate of #2013

**Comment by Plant-for-the-Planet** [comment] 2020-04-10 14:30
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/pledge/mandoki-soulmates**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fb88afa900193f7dde?event_id=5e9082f60059ae58cc840000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-04-11 02:24
Duplicate of #2012

**Closed by norbertschuler** 2020-04-11 02:24 UTC
Labels: 1.3.1, bug, bugsnag, production
