### ISSUE TITLE
TypeError in /gift-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1221] opened 2019-08-12 05:57 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
Cannot read property 'treecounter' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d50ffcca2a4a50018dabcd5?event_id=5d50ffcc004cc8c1d13b0000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/bundle.js:122142 - GiftTrees.t.checkValidation

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d50ffcca2a4a50018dabcd5?event_id=5d50ffcc004cc8c1d13b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-12 06:47
Duplicate of #1216

**Closed by norbertschuler** 2019-08-12 06:47 UTC
Labels: 1.0.5, bug, bugsnag, production
