### ISSUE TITLE
java.lang.IllegalStateException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1294] opened 2019-08-23 22:39 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d606b113d4e9e001947438e?event_id=5d606b11004dc319f1c80000&i=gh&m=ci)

## Stacktrace

    SourceFile:94 - nba.a

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d606b113d4e9e001947438e?event_id=5d606b11004dc319f1c80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-17 12:06
Duplicate of #1405

**Closed by norbertschuler** 2019-09-17 12:06 UTC
Labels: 1.0.5, bug, bugsnag, production
