### ISSUE TITLE
TypeError in app/selectors/index.js:215 - undefined is not an object (evaluating 't[l].category='contributions'')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2051] opened 2020-03-13 12:33 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **app/selectors/index.js:215**
undefined is not an object (evaluating 't[l].category='contributions'')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6b7d977a504e001702f2fc?event_id=5e6b7d97005829b855970000&i=gh&m=ci)

## Stacktrace

    app/selectors/index.js:215 - 
    app/containers/UserHome/index.js:60 - 
    app/actions/EditMyTree.js:86 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6b7d977a504e001702f2fc?event_id=5e6b7d97005829b855970000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 06:28
Duplicate of #1910

**Closed by norbertschuler** 2020-04-02 06:28 UTC
Labels: 1.49.4, bug, bugsnag, production
