### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2976] opened 2021-03-20 10:34 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6055cfb6dbed42000707896e?event_id=6055cfb600754b7292b60000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3982896 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6055cfb6dbed42000707896e?event_id=6055cfb600754b7292b60000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:34
Duplicate of #2979

**Closed by norbertschuler** 2021-03-29 07:34 UTC
Labels: 1.4.0, bug, bugsnag, production
