### ISSUE TITLE
ReferenceError in /donate-trees/1 - Intl is not defined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2676] opened 2020-08-26 20:05 UTC
## Error in Plant-for-the-Planet App

**ReferenceError** in **/donate-trees/1**
Intl is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f46c0816775440017a38854?event_id=5f46c081005dfb545c7c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/15.ee141c985c359aa36486.js:1 - getMonthsForLocale

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f46c0816775440017a38854?event_id=5f46c081005dfb545c7c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-08-28 08:14
Duplicate of #2644

**Closed by norbertschuler** 2020-08-28 08:14 UTC
Labels: 1.3.6, bug, bugsnag, production
