### ISSUE TITLE
SIGSEGV in MainActivity - /system/lib64/libhwui.so:2694688 - SkSurface::getCanvas()

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2970] opened 2021-03-14 22:24 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/604e8d0c4385320007a1b77d?event_id=604e8d0c0073af97febb0000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:2694688 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/604e8d0c4385320007a1b77d?event_id=604e8d0c0073af97febb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:33
Duplicate of #2979

**Comment by Plant-for-the-Planet** [comment] 2021-06-27 17:26
An error linked to this issue has been reopened in Bugsnag
[**SIGSEGV** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/604e8d0c4385320007a1b77d?event_id=60d8b4b6007f606d54420000&i=gh&m=ra)

**Closed** 2021-08-06 10:26 UTC
Labels: bug, bugsnag, production, 1.4.0
