### ISSUE TITLE
TypeError in /explore - Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2668] opened 2020-08-24 17:51 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/explore**
Cannot read property 'description' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f43fe1d34dfa30017634ac7?event_id=5f43fe1d005df35e1e7a0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/18.ee141c985c359aa36486.js:1 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f43fe1d34dfa30017634ac7?event_id=5f43fe1d005df35e1e7a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-08-25 10:12
Duplicate of #2671

**Closed by norbertschuler** 2020-08-25 10:12 UTC
Labels: 1.3.6, bug, bugsnag, production
