### ISSUE TITLE
Error in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1212] opened 2019-08-09 23:57 UTC
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d4e0871b07560001d0beeab?event_id=5d4e0871004ce29d8e810000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/app/components/Common/LoadingIndicator.js:6 - LoadingIndicator

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d4e0871b07560001d0beeab?event_id=5d4e0871004ce29d8e810000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-12 14:44
Duplicate of #1014

**Closed by norbertschuler** 2019-08-12 14:44 UTC
Labels: 1.0.3, bug, bugsnag, production
