### ISSUE TITLE
Error in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2036] opened 2020-03-09 14:54 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e665892ef027500170506fd?event_id=5e6658920058324c37a10000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.0d25526daeff53af28a3.js:1 - normalize

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e665892ef027500170506fd?event_id=5e6658920058324c37a10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by harshvitra** [comment] 2020-03-12 19:35
Cannot replicate this

**Comment by norbertschuler** [comment] 2020-03-12 20:07
This probably only happens, if the backend returns some results that can not be processed. But I also can not reproduce this.

**Comment by norbertschuler** [comment] 2020-04-02 05:58
Duplicate of #2029

**Closed by norbertschuler** 2020-04-02 05:58 UTC
Labels: 1.3.1, bug, bugsnag, production
