### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2973] opened 2021-03-15 18:07 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/604fa250ac69c70007ee989a?event_id=604fa2500073ae7f27c00000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3803328 - 0x750c0768c0

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/604fa250ac69c70007ee989a?event_id=604fa2500073ae7f27c00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:35
Duplicate of #2982

**Closed by norbertschuler** 2021-03-29 07:35 UTC
Labels: 1.4.0, bug, bugsnag, production
