### ISSUE TITLE
TypeError in /signup - lt.default.notify is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2072] opened 2020-03-25 13:31 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/signup**
lt.default.notify is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7b5d2967f0ac001814b036?event_id=5e7b5d2900591f6a26eb0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.a9833345c1c673bdace7.js:1 - GlobalErrorBoundary.componentDidCatch

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7b5d2967f0ac001814b036?event_id=5e7b5d2900591f6a26eb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 06:35
this is related to 
Duplicate of #1946

**Comment by Plant-for-the-Planet** [comment] 2020-05-07 15:56
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7b5d2967f0ac001814b036?event_id=5eb42f92005b3be956230000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-06-10 06:57
Could also be caused by "ChunkLoadError: Loading chunk 50 failed" meaning some Chunk of our JavaScript code could not be loaded.

**Closed by norbertschuler** 2020-06-10 06:57 UTC
Labels: 1.3.2, bug, bugsnag, production
