### ISSUE TITLE
Register - "Add a Tree" Button broken - Easter soon

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2161] opened 2020-04-06 14:42 UTC
**After filling out register form, clicking 'Add a Tree' doesn't trigger any events**
This is the case for Single tree and Many Trees.

**This is a bug on the production app. The Web-App doesn't have this issue. iOS I am unsure about.**

**This is important as we expect quite a lot of users to come to the app at Easter (because of Baumgeschenke, spring starting now, holidays, etc.**
Because of the spring part, I just received three different failed registered trees -  all this problem.
And I tried myself ==> same problem.

**To Reproduce**
1. Go to "Me"
2. Click on "Register Tree"
3. Enter information and choose location
4. Press Button: Add a Tree
5. Nothing happens

**Expected behavior**
Either one:
1. A message telling me that my input was wrong
2. It adding the tree(s) to my trees

**Smartphone:**
- Device: Samsung Galaxy S7
- OS: Android 8.0.0
- Samsung Experience version: 9.0
- Plant-for-the-Planet App Version 1.3.2.900027

Thanks for your time!

**Comment by norbertschuler** [comment] 2020-04-06 15:23
Duplicate of #2119

**Closed** 2020-04-07 14:13 UTC
Labels: Android, bug, help wanted, production
