### ISSUE TITLE
java.lang.RuntimeException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3126] opened 2021-10-29 15:02 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **MainActivity**
Unable to resume activity {org.pftp/org.pftp.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.facebook.react.bridge.Callback com.zoontek.rnpermissions.RNPermissionsModule$Request.callback' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/617c0d1ae7d64800079e1f96?event_id=617c0d1a00897ac9282a0000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4014 - android.app.ActivityThread.performResumeActivity

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/617c0d1ae7d64800079e1f96?event_id=617c0d1a00897ac9282a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2022-06-08 19:22
Duplicate of #3162

**Closed by norbertschuler** 2022-06-08 19:22 UTC
Labels: bug, bugsnag, production, native, 1.4.7
