### ISSUE TITLE
Paypal error - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1943] opened 2020-02-13 13:21 UTC
## Error in Plant-for-the-Planet App

**Error** in **/gift-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e454d57573fc200192913ca?event_id=5e454d570055e45893af0000&i=gh&m=ci)

## Stacktrace

    app/actions/donateAction.js:132 - finalizeDonation/</<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e454d57573fc200192913ca?event_id=5e454d570055e45893af0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-01 14:43
This looks like a problem when the Paypal payment process with the external window is used. (Maybe cancelled.)

**Comment by norbertschuler** [comment] 2020-09-17 14:16
Duplicate of #2725

**Closed by norbertschuler** 2020-09-17 14:16 UTC
Labels: 1.3.1, bug, bugsnag, production
