### ISSUE TITLE
TypeError in app/components/UserContributions/ContributionDetails/index.native.js:140 - undefined is not an object (evaluating 'z.charAt')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2008] opened 2020-02-27 10:40 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/UserContributions/ContributionDetails/index.native.js:140**
undefined is not an object (evaluating 'z.charAt')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e579ca9af3b19001a22c1a8?event_id=5e579ca90055eaf1c90d0000&i=gh&m=ci)

## Stacktrace

    app/components/UserContributions/ContributionDetails/index.native.js:140 - value

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e579ca9af3b19001a22c1a8?event_id=5e579ca90055eaf1c90d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 05:36
Maybe add some safety check?

<img width="655" alt="Bildschirmfoto 2020-04-02 um 12 36 24" src="https://user-images.githubusercontent.com/1532418/78214105-959ede80-74de-11ea-9dcd-4ddd8aeb166a.png">

**Comment by norbertschuler** [comment] 2020-04-12 15:38
Duplicate of #2200

**Closed by norbertschuler** 2020-04-12 15:38 UTC
Labels: 1.49.4, bug, bugsnag, production
