### ISSUE TITLE
SoLoader.java:738 - com.facebook.soloader.SoLoader.doLoadLibraryBySoName

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2999] opened 2021-04-15 04:05 UTC
## Error in Plant-for-the-Planet App

**java.lang.UnsatisfiedLinkError** in **SoLoader.java:738**
couldn't find DSO to load: libhermes.so

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6077bb9eb7f7960008fafbff?event_id=6077bb9e00777559c1fb0000&i=gh&m=ci)

## Stacktrace

    SoLoader.java:738 - com.facebook.soloader.SoLoader.doLoadLibraryBySoName

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6077bb9eb7f7960008fafbff?event_id=6077bb9e00777559c1fb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-04-20 14:17
Duplicate of #3000

**Closed by norbertschuler** 2021-04-20 14:17 UTC
Labels: 1.3.6, bug, bugsnag, production
