### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2967] opened 2021-03-10 14:35 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6048d91476dc910007fae275?event_id=6048d9140072f0c554d80000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3794928 - 0x79087e07f0

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6048d91476dc910007fae275?event_id=6048d9140072f0c554d80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:35
Duplicate of #2982

**Closed by norbertschuler** 2021-03-29 07:35 UTC
Labels: 1.4.0, bug, bugsnag, production
