### ISSUE TITLE
java.lang.RuntimeException in Binder.java:622

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1600] opened 2019-11-06 16:40 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:622**
android.os.TransactionTooLargeException: data parcel size 622160 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc2f76ec4a99a001a09549d?event_id=5dc2f76e005296d758630000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:3873 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc2f76ec4a99a001a09549d?event_id=5dc2f76e005296d758630000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:50
Duplicate of #1745

**Closed by norbertschuler** 2019-12-13 07:50 UTC
Labels: 1.1.0, bug, bugsnag, production
