### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2219] opened 2020-04-22 00:03 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **Editor.java:6718**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5e9f89c4005a2c44aa850000&i=gh&m=ci)

## Stacktrace

    Editor.java:6718 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5e9f89c4005a2c44aa850000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-05-03 11:25
do not fix native bugs yet

**Comment by Plant-for-the-Planet** [comment] 2020-05-11 19:16
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **Editor.java:6718**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5eb9a46e005b2c1257f90000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-06-02 11:08
Related or duplicate of #2335

**Comment by norbertschuler** [comment] 2020-06-22 11:41
Duplicate of #2084

**Comment by Plant-for-the-Planet** [comment] 2020-07-03 11:42
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **Editor.java:6718**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5eff19a7005b6f210da40000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment] 2020-08-19 06:56
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **Editor.java:6718**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5f3ccd21005b8044fba20000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-08-24 07:27
Duplicate of #2335

**Comment by Plant-for-the-Planet** [comment] 2020-08-30 16:47
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5f4bd811005ded6635b10000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-09-17 14:06
Duplicate of #2711

**Comment by Plant-for-the-Planet** [comment] 2020-10-07 14:28
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=5f7dd06f00615bc5210a0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-12-18 08:13
Duplicate of #2711

**Comment by Plant-for-the-Planet** [comment] 2021-01-20 15:42
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9f89c48d5c820017e80dcf?event_id=60084f4d0069b33b3d880000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2021-04-20 14:15
Duplicate of #2741

**Closed by norbertschuler** 2021-04-20 14:15 UTC
Labels: bug, bugsnag, native, production
