### ISSUE TITLE
java.lang.IllegalStateException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1470] opened 2019-09-25 14:29 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b79c270f3d5001b9fa5f6?event_id=5d8b79c2005045b4cbc80000&i=gh&m=ci)

## Stacktrace

    PG:58 - ndn.aa

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b79c270f3d5001b9fa5f6?event_id=5d8b79c2005045b4cbc80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-26 09:14
Duplicate of #1405

**Closed by norbertschuler** 2019-09-26 09:14 UTC
Labels: 1.0.8, bug, bugsnag, production
