### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3081] opened 2021-08-09 00:01 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6110704546797900088c5fd5?event_id=61107045007f98b1b5a90000&i=gh&m=ci)

## Stacktrace

    Editor.java:6718 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6110704546797900088c5fd5?event_id=61107045007f98b1b5a90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-09-08 13:54
Duplicate of #2741

**Comment by Plant-for-the-Planet** [comment] 2021-09-09 11:44
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6110704546797900088c5fd5?event_id=6139f3a800808cd2b8500000&i=gh&m=ra)

**Closed** 2022-06-08 19:11 UTC
Labels: bug, bugsnag, production, native, 1.4.4
