### ISSUE TITLE
Unable to create layer for ReactHorizontalScrollContainerView

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2327] opened 2020-05-08 12:58 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
Unable to create layer for ReactHorizontalScrollContainerView

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb55768c56d100017f163ce?event_id=5eb55768005b4bbffb840000&i=gh&m=ci)

## Stacktrace

```java
java.lang.IllegalStateException Unable to create layer for ReactHorizontalScrollContainerView 
    MessageQueue.java:-2 android.os.MessageQueue.nativePollOnce
    MessageQueue.java:323 android.os.MessageQueue.next
    Looper.java:135 android.os.Looper.loop
    ActivityThread.java:5417 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:726 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:616 com.android.internal.os.ZygoteInit.main

```
[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb55768c56d100017f163ce?event_id=5eb55768005b4bbffb840000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment] 2020-05-08 12:59
Happened to me on my Nexus 7 with Android 6 deleting a user contribution.

Comment added in Bugsnag by Norbert Schuler
[**java.lang.IllegalStateException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb55768c56d100017f163ce?event_id=5eb55768005b4bbffb840000&i=gh&m=cm)

**Comment by Plant-for-the-Planet** [comment] 2020-05-08 13:00
Correction: happening when closing detail view of user contribution.

Comment added in Bugsnag by Norbert Schuler
[**java.lang.IllegalStateException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb55768c56d100017f163ce?event_id=5eb557d9005b361246410000&i=gh&m=cm)

**Comment by norbertschuler** [comment] 2020-09-17 14:07
Duplicate of #2560

**Closed by norbertschuler** 2020-09-17 14:07 UTC
Labels: 1.3.3, bug, bugsnag, native, production
