### ISSUE TITLE
Handle 401 JWT Expirations by sending to login Screen

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1611] opened 2019-11-08 17:12 UTC
Got this error while updating a competition shortly after creating it.
<img width="1157" alt="Screen Shot 2019-11-08 at 6 11 43 PM" src="https://user-images.githubusercontent.com/5401575/68496739-4ddb9a00-0253-11ea-9caf-abfb1e0345c7.png">

**Comment by harshvitra** [comment] 2020-05-02 21:00
Does this happen even now ? 
@sagararyal @norbertschuler

**Comment by norbertschuler** [comment] 2020-05-03 06:48
I think it still happens. Especially if you use the same account on different devices, e.g. iPhone, Android and web client. But for normal users, this probably happens very rarely.

**Comment by norbertschuler** [comment] 2020-05-03 06:48
This is not related to competitions. It's a general bug which could happen anywhere in the app!

**Comment by norbertschuler** [comment] 2020-05-03 08:59
In my tests (setting the AsyncStore values manually to empty in the web client or native apps) the user was successfully logged out showing the login screen on the web client, but the welcome screen on the native apps. Can we close this?

**Comment by Plant-for-the-Planet** [comment] 2020-05-03 10:06
Please close if you cannot reproduce this any more.

**Closed** 2020-05-08 05:53 UTC
Labels: bug, enhancement
