### ISSUE TITLE
Error in app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:141

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2804] opened 2020-10-13 14:02 UTC
## Error in Plant-for-the-Planet App

**Error** in **app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:141**
Unable to open URL: mailto:louise.tideman@weforest.org?subject=Re:WeForest%20at%20Plant-for-the-Planet%20App

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f85b38f42bb600017d9269b?event_id=5f85b38f006165eeec810000&i=gh&m=ci)

## Stacktrace

    app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:141 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f85b38f42bb600017d9269b?event_id=5f85b38f006165eeec810000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-12-20 14:39
Duplicate of #2910

**Closed by norbertschuler** 2020-12-20 14:39 UTC
Labels: 1.49.45, bug, bugsnag, production
