### ISSUE TITLE
window.onerror in /gift-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1019] opened 2019-07-01 18:12 UTC
## Error in Plant-for-the-Planet App

**window.onerror** in **/gift-trees**
TypeError: undefined is not an object (evaluating 't.state.form.directGift.treecounter')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d1a4d036aa6cf001abab681?event_id=5d1a4d0300467a2f11c00000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:17 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d1a4d036aa6cf001abab681?event_id=5d1a4d0300467a2f11c00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-07-15 06:21
There is also still something as `let value = this.refs.donateReceipt.getValue();` app/components/GiftTrees/index.js - we changed that already in app/components/DonateTrees/index.js to `let value = this.refs.donateReceipt && this.refs.donateReceipt.getValue();` to be more failsafe.

**Comment by norbertschuler** [comment] 2019-08-14 14:27
Duplicate of #1216

**Closed by norbertschuler** 2019-08-14 14:27 UTC
Labels: bug, bugsnag
