### ISSUE TITLE
Error in / - Request failed with status code 404

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2545] opened 2020-07-20 00:47 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 404

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f14e9a50c63740017961d27?event_id=5f14e9a5005b742065b00000&i=gh&m=ci)

## Stacktrace

    app/utils/api.js:86 - _callee4$

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f14e9a50c63740017961d27?event_id=5f14e9a5005b742065b00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-08-13 08:47
Duplicate of #2590

**Closed by norbertschuler** 2020-08-13 08:47 UTC
Labels: 1.3.4, bug, bugsnag, production
