### ISSUE TITLE
TypeError in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1981] opened 2020-02-19 18:28 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/**
a[b].target.className.indexOf is not a function. (In 'a[b].target.className.indexOf(ac)', 'a[b].target.className.indexOf' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4d7e3601e05d0019b10de8?event_id=5e4d7e360055f6d9e7670000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/:412 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4d7e3601e05d0019b10de8?event_id=5e4d7e360055f6d9e7670000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 05:21
I cannot reproduce this due to missing stack trace. Also this only happen once for one user, so I am closing it for now.

**Closed by norbertschuler** 2020-04-02 05:21 UTC
Labels: 1.3.1, bug, bugsnag, production
