### ISSUE TITLE
TypeError in main.jsbundle:2506

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2616] opened 2020-08-13 19:35 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **main.jsbundle:2506**
undefined is not an object (evaluating 't.response.data')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f3595f1f276cb00174a4f3d?event_id=5f3595f1005b6df360620000&i=gh&m=ci)

## Stacktrace

    main.jsbundle:2506 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f3595f1f276cb00174a4f3d?event_id=5f3595f1005b6df360620000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-08-14 10:38
Duplicate of #2617

**Closed** 2020-08-14 10:38 UTC
Labels: 1.49.44, bug, bugsnag, production
