### ISSUE TITLE
window.onerror in /donate-trees/1 - TypeError: At.default.notify is not a function. (In 'At.default.notify(E,(function(E){E.metadata={info:j}}))', 'At.default.notify' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2421] opened 2020-06-08 21:59 UTC
## Error in Plant-for-the-Planet App

**window.onerror** in **/donate-trees/1**
TypeError: At.default.notify is not a function. (In 'At.default.notify(E,(function(E){E.metadata={info:j}}))', 'At.default.notify' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edeb4b27f912c00184996b1?event_id=5edeb4b2005b770501880000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/20.aadf72caf807716c6723.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edeb4b27f912c00184996b1?event_id=5edeb4b2005b770501880000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 12:35
Duplicate of #2388

**Closed by norbertschuler** 2020-06-22 12:35 UTC
Labels: 1.3.4, bug, bugsnag, production
