### ISSUE TITLE
Error in /donate-trees - data of response if empty

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2615] opened 2020-08-13 12:59 UTC
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
[object Object]

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f353940d66d330017366e7b?event_id=5f353940005b72a0a3a30000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.8f6fd118dff9c3fa204b.js:1 - checkStatus

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f353940d66d330017366e7b?event_id=5f353940005b72a0a3a30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment] 2020-08-24 11:47
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f353940d66d330017366e7b?event_id=5f43a8c8005df52c55690000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-08-25 10:18
Duplicate of #2640

**Comment by Plant-for-the-Planet** [comment] 2020-08-26 06:26
accidentally closed wrong error

Comment added in Bugsnag by Norbert Schuler
[**Error** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f353940d66d330017366e7b?event_id=5f45f89a005e074d43860000&i=gh&m=cm)

**Closed** 2020-12-20 14:45 UTC
Labels: 1.3.5, bug, bugsnag, production
