### ISSUE TITLE
Error in /home

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2535] opened 2020-07-17 05:02 UTC
## Error in Plant-for-the-Planet App

**Error** in **/home**
Request failed with status code 500

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1130c8eaae8b0017c0a321?event_id=5f1130c8005b6e4f142b0000&i=gh&m=ci)

## Stacktrace

    https://development.trilliontreecampaign.org/bundle.ec75d9abf09aa40b7709.js:2 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1130c8eaae8b0017c0a321?event_id=5f1130c8005b6e4f142b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-07-17 05:02
Duplicate of #2534

**Closed by norbertschuler** 2020-07-17 05:02 UTC
Labels: 1.3.5, bug, bugsnag, production
