### ISSUE TITLE
java.lang.NullPointerException in ArrayDeque.java:228

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1907] opened 2020-02-06 11:41 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **ArrayDeque.java:228**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e3bfb5ea95e5000194459d5?event_id=5e3bfb5e0055f9ffee360000&i=gh&m=ci)

## Stacktrace

    ArrayDeque.java:228 - java.util.ArrayDeque.addLast

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e3bfb5ea95e5000194459d5?event_id=5e3bfb5e0055f9ffee360000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-10 07:59
Duplicate of #2197

**Closed by norbertschuler** 2020-04-10 07:59 UTC
Labels: 1.3.0, bug, bugsnag, native, production
