### ISSUE TITLE
TypeError in MainActivity - undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2382] opened 2020-06-02 17:41 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed68f3926f156001880a149?event_id=5ed68f39005b6919ce310000&i=gh&m=ci)

## Stacktrace

    app/actions/trillionAction.js:6 - _renderScreen
    app/actions/trillionAction.js:6 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed68f3926f156001880a149?event_id=5ed68f39005b6919ce310000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 12:26
Duplicate of #2354

**Closed by norbertschuler** 2020-06-22 12:26 UTC
Labels: 1.3.3, bug, bugsnag, production
