### ISSUE TITLE
SIGSEGV in MainActivity - /system/lib64/libhwui.so:3860960 - SkSurface::getCanvas()

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2944] opened 2021-02-07 22:59 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/602070da3e8c7500178613c9?event_id=602070da00699a7083b60000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3860960 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/602070da3e8c7500178613c9?event_id=602070da00699a7083b60000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:33
Duplicate of #2979

**Comment by Plant-for-the-Planet** [comment] 2021-04-22 11:12
An error linked to this issue has been reopened in Bugsnag
[**SIGSEGV** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/602070da3e8c7500178613c9?event_id=60815a010077c11cb4dc0000&i=gh&m=ra)

**Closed** 2021-08-06 10:24 UTC
Labels: bug, bugsnag, production, 1.3.9
