### ISSUE TITLE
Error in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1438] opened 2019-09-19 11:46 UTC
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
Request failed with status code 401

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d836a89444120001a329211?event_id=5d836a8900504ea145410000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:36155 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d836a89444120001a329211?event_id=5d836a8900504ea145410000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-23 11:32
Duplicate of #1427

**Closed by norbertschuler** 2019-09-23 11:32 UTC
Labels: 1.0.8, bug, bugsnag, production
