### ISSUE TITLE
SIGSEGV in MainActivity - /system/lib64/libhwui.so:2566180 - SkSurface::getCanvas()

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2942] opened 2021-02-06 08:38 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/601e556e5d0bee00173039f3?event_id=601e556e0069a0a34ce30000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:2566180 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/601e556e5d0bee00173039f3?event_id=601e556e0069a0a34ce30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:33
Duplicate of #2979

**Comment by Plant-for-the-Planet** [comment] 2021-04-02 07:53
An error linked to this issue has been reopened in Bugsnag
[**SIGSEGV** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/601e556e5d0bee00173039f3?event_id=6066cd6a0076024e2eac0000&i=gh&m=ra)

**Closed** 2021-08-06 10:24 UTC
Labels: bug, bugsnag, production, 1.3.9
