### ISSUE TITLE
TypeError in /login - Cannot read property '6Ldl8WoUAAAAAGj0OIKqbvkm_XiDPbve07JJySBF' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2704] opened 2020-09-02 05:55 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
Cannot read property '6Ldl8WoUAAAAAGj0OIKqbvkm_XiDPbve07JJySBF' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4f33e63a49a30017bfc16f?event_id=5f4f33e6005df6d405cf0000&i=gh&m=ci)

## Stacktrace

    https://www.gstatic.com/recaptcha/releases/NjbyeWjjFy97MXGZ40KrXu3v/recaptcha__de.js:253 - Array.<anonymous>

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4f33e63a49a30017bfc16f?event_id=5f4f33e6005df6d405cf0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-09-17 14:19
Duplicate of #2706

**Closed by norbertschuler** 2020-09-17 14:19 UTC
Labels: 1.3.6, bug, bugsnag, production
