### ISSUE TITLE
TypeError in app/containers/EditCompetition/index.js:70

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1198] opened 2019-08-05 11:50 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **app/containers/EditCompetition/index.js:70**
null is not an object (evaluating 't.imageFile.includes')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d481818b28776001a5ecad6?event_id=5d481818004c1adb5c410000&i=gh&m=ci)

## Stacktrace

    app/containers/EditCompetition/index.js:70 - value
    app/components/Competition/EditCompetition.native.js:139 - value
    app/components/Competition/EditCompetition.native.js:165 - onClick
    app/components/Common/Button/PrimaryButton.native.js:15 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d481818b28776001a5ecad6?event_id=5d481818004c1adb5c410000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-10-10 10:12
Duplicate of #1532

**Closed by norbertschuler** 2019-10-10 10:12 UTC
Labels: 1.44, bug, bugsnag, production
