### ISSUE TITLE
java.lang.RuntimeException in Binder.java:761

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1703] opened 2019-12-04 18:12 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:761**
android.os.TransactionTooLargeException: data parcel size 650820 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5de7f70dcd4e97001981dc90?event_id=5de7f70d00540aad42420000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4156 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5de7f70dcd4e97001981dc90?event_id=5de7f70d00540aad42420000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:48
Duplicate of #1745

**Comment by norbertschuler** [comment] 2019-12-13 07:51
Duplicate of #1745

**Comment by Plant-for-the-Planet** [comment] 2020-01-18 20:19
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **Binder.java:761**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5de7f70dcd4e97001981dc90?event_id=5e236848005600ade81a0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-01-18 21:38
native error

**Closed by norbertschuler** 2020-01-18 21:38 UTC
Labels: bug, bugsnag, production
