### ISSUE TITLE
java.lang.RuntimeException in Binder.java:753

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1603] opened 2019-11-07 16:22 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:753**
android.os.TransactionTooLargeException: data parcel size 618492 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc444d88b24c6001a35469f?event_id=5dc444d80052c83d75840000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4720 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc444d88b24c6001a35469f?event_id=5dc444d80052c83d75840000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:50
Duplicate of #1745

**Closed by norbertschuler** 2019-12-13 07:50 UTC
Labels: 1.1.1, bug, bugsnag, production
