### ISSUE TITLE
RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1ccf5fbf0' was thrown while invoking multiSet on target RNCAsyncStorage with params (         (                 (             token,             "<null>"         )     ),     19811 ) callstack: ( 	0   CoreFoundation                      0x000000019c42e3c0 <redacted> + 256 	1   libobjc.A.dylib                     0x000000019b633d00 objc_exception_throw + 60 	2   CoreFoundation                      0x000000... in facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1606] opened 2019-11-08 07:47 UTC
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1ccf5fbf0' was thrown while invoking multiSet on target RNCAsyncStorage with params (         (                 (             token,             "<null>"         )     ),     19811 ) callstack: ( 	0   CoreFoundation                      0x000000019c42e3c0 <redacted> + 256 	1   libobjc.A.dylib                     0x000000019b633d00 objc_exception_throw + 60 	2   CoreFoundation                      0x000000...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x1ccf5fbf0' was thrown while invoking multiSet on target RNCAsyncStorage with params (
        (
         ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc51d8490ee74001a87164b?event_id=5dc51d840052b7e2135d0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc51d8490ee74001a87164b?event_id=5dc51d840052b7e2135d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-11-08 08:01
Duplicate of #1511

**Closed by norbertschuler** 2019-11-08 08:01 UTC
Labels: 1.49.1, bug, bugsnag, production
