### ISSUE TITLE
TypeError in /signup/vodafone

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2478] opened 2020-06-22 07:06 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/signup/vodafone**
this.props.onProfileClick is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef0587f26fb1200177f2573?event_id=5ef0587f005b8e3a15790000&i=gh&m=ci)

## Stacktrace

    app/components/Authentication/SignUp/SignUpType.js:12 - SignUpType.OnProfileClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef0587f26fb1200177f2573?event_id=5ef0587f005b8e3a15790000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 07:07
Duplicate of #1954

**Closed by norbertschuler** 2020-06-22 07:07 UTC
Labels: 1.3.4, bug, bugsnag, production
