### ISSUE TITLE
YouTubePlayer has been released

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1405] opened 2019-09-11 08:13 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d78aca69230090019fafb32?event_id=5d78aca6004f330337120000&i=gh&m=ci)

## Stacktrace

    SourceFile:91 - nqd.aa

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d78aca69230090019fafb32?event_id=5d78aca6004f330337120000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-09-29 07:53
Duplicate of #1488

**Closed by norbertschuler** 2019-09-29 07:53 UTC
Labels: 1.0.7, bug, bugsnag, production
