### ISSUE TITLE
Error in / - Request failed with status code 404

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2049] opened 2020-03-12 22:10 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 404

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6ab36df7c18900181b5d5b?event_id=5e6ab36d00580e0455540000&i=gh&m=ci)

## Stacktrace

    app/containers/PublicTreeCounterContainer/index.js:40 - fetchAndSetSearchResult
    app/containers/PublicTreeCounterContainer/index.js:51 - UNSAFE_componentWillMount

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6ab36df7c18900181b5d5b?event_id=5e6ab36d00580e0455540000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-03-25 12:56
Duplicate of #2071

**Comment by norbertschuler** [comment] 2020-04-02 05:58
server error

**Comment by Plant-for-the-Planet** [comment] 2020-04-17 18:50
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6ab36df7c18900181b5d5b?event_id=5e99fa7e0059f7f075640000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-06-22 10:59
Outdated

**Closed by norbertschuler** 2020-06-22 10:59 UTC
Labels: 1.3.1, bug, bugsnag, production
