### ISSUE TITLE
java.lang.RuntimeException in Binder.java:751

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1909] opened 2020-02-06 15:40 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:751**
android.os.TransactionTooLargeException: data parcel size 541928 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e3c335b0f1222001a753a72?event_id=5e3c335b0055f660351e0000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4611 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e3c335b0f1222001a753a72?event_id=5e3c335b0055f660351e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 06:54
Duplicate of #1978

**Closed by norbertschuler** 2020-04-02 06:54 UTC
Labels: 1.3.0, bug, bugsnag, native, production
