### ISSUE TITLE
Error in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1427] opened 2019-09-16 06:42 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 401

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d7f2edde8e63800194a61f6?event_id=5d7f2edd004fd4919ec50000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:36249 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d7f2edde8e63800194a61f6?event_id=5d7f2edd004fd4919ec50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment] 2019-09-16 07:19
Hopefully this does not happen to our users.

Comment added in Bugsnag by Norbert Schuler
[**Error** in **/**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d7f2edde8e63800194a61f6?event_id=5d7f2edd004fd4919ec50000&i=gh&m=cm)

**Comment by norbertschuler** [comment] 2019-09-26 14:50
Duplicate of #1291 1477

**Closed by norbertschuler** 2019-09-26 14:50 UTC
Labels: 1.0.8, bug, bugsnag, production
