### ISSUE TITLE
TypeError in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2495] opened 2020-06-25 04:26 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'plantProjectPager' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef4276f6fb0fc001806ba7c?event_id=5ef4276f005b7afb670c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/15.8aff6290fd07f2539028.js:1 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef4276f6fb0fc001806ba7c?event_id=5ef4276f005b7afb670c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-25 06:06
Duplicate of #2418

**Closed by norbertschuler** 2020-06-25 06:06 UTC
Labels: 1.3.4, bug, bugsnag, production
