### ISSUE TITLE
TypeError in /t/oskar-de-gmbh - Object.values is not a function. (In 'Object.values(t)', 'Object.values' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2680] opened 2020-08-27 13:22 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/t/oskar-de-gmbh**
Object.values is not a function. (In 'Object.values(t)', 'Object.values' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f47b3a19663c80018f481cb?event_id=5f47b3a1005dea49a2fd0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/5.ee141c985c359aa36486.js:1 - componentDidMount

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f47b3a19663c80018f481cb?event_id=5f47b3a1005dea49a2fd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-09-17 14:20
Duplicate of #2693

**Closed by norbertschuler** 2020-09-17 14:20 UTC
Labels: 1.3.6, bug, bugsnag, production
