### ISSUE TITLE
Error in app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:137

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1941] opened 2020-02-13 10:13 UTC
## Error in Plant-for-the-Planet App

**Error** in **app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:137**
Unable to open URL: mailto:miguel@conservenaturalforests.org?subject=Re:Conserve%20Natural%20Forests%20at%20Plant-for-the-Planet%20App

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4521433e889e001a17e1c5?event_id=5e4521430056033745760000&i=gh&m=ci)

## Stacktrace

    app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:137 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4521433e889e001a17e1c5?event_id=5e4521430056033745760000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-01 14:40
The mailto link looks ok and works on my device. Closing this for now as I cannot reproduce it.

**Closed by norbertschuler** 2020-04-01 14:40 UTC
Labels: 1.49.3, bug, bugsnag, production
