### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2769] opened 2020-10-04 15:52 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f79efcaf3000c00176324c5?event_id=5f79efca0061529743c00000&i=gh&m=ci)

## Stacktrace

    Editor.java:6915 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f79efcaf3000c00176324c5?event_id=5f79efca0061529743c00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-10-04 15:55
Duplicate of #2741

**Closed by norbertschuler** 2020-10-04 15:55 UTC
Labels: 1.3.7, bug, bugsnag, native, production
