### ISSUE TITLE
TypeError in app/components/TreecounterGraphics/Trillion.native.js:181

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1505] opened 2019-10-02 21:18 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/TreecounterGraphics/Trillion.native.js:181**
TypeError: TypeError: TypeError: TypeError: undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

This error is located at:
    in n
    in l
    in _
    in s
    in RCTView
    in RCTView
    in l
    in RCTView
    in n
    in RCTView
    in n
    in s
    in h
    in w
    in s
    in RCTView
    in l
    in n
    in n
    in E
    in RCTView
    in n
    in RCTView
    in s
    in L
    in RCTView
    in s
    in o
    in h
    in _
    in w
    in s
    in RCTView
    in l
    in RCTView
    in n
    in _
    in h
    in w
    in RCTView
    in o
    in _
    in RCTView
    in l
    in n
    in p
    in n
    in _
    in y
    in f
    in u
    in RCTView
    in RCTView
    in Unknown
    in RCTView
    in c

This error is located at:
    in w
    in s
    in RCTView
    in l
    in n
    in n
    in E
    in RCTView
    in n
    in RCTView
    in s
    in L
    in RCTView
    in s
    in o
    in h
    in _
    in w
    in s
    in RCTView
    in l...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d95142ab7788a001aab943b?event_id=5d95142a0050311149080000&i=gh&m=ci)

## Stacktrace

    app/components/TreecounterGraphics/Trillion.native.js:181 - _renderScreen
    app/components/TreecounterGraphics/Trillion.native.js:82 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d95142ab7788a001aab943b?event_id=5d95142a0050311149080000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-15 12:07
Duplicate of #1756

**Closed by norbertschuler** 2019-12-15 12:07 UTC
Labels: 1.49, bug, bugsnag, production
