### ISSUE TITLE
TypeError in /gift-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1501] opened 2019-10-01 12:41 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
Cannot read property 'amount' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d934971cec80d00198f2da9?event_id=5d934971005038c7847f0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:122800 - PaymentSelector.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d934971cec80d00198f2da9?event_id=5d934971005038c7847f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-10-01 12:43
Duplicate of #1120

**Closed by norbertschuler** 2019-10-01 12:43 UTC
Labels: 1.1.0, bug, bugsnag, production
