### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2937] opened 2021-01-24 07:31 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/600d2266b530c4001868c1b1?event_id=600d22660069a1a320a90000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3834820 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/600d2266b530c4001868c1b1?event_id=600d22660069a1a320a90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:32
Duplicate of #2979

**Closed by norbertschuler** 2021-03-29 07:32 UTC
Labels: 1.3.9, bug, bugsnag, native, production
