### ISSUE TITLE
java.lang.IllegalStateException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1533] opened 2019-10-09 23:04 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d9e6765798e6d001aa0dc95?event_id=5d9e67650050dc0e8d920000&i=gh&m=ci)

## Stacktrace

    PG:62 - mzi.aa

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d9e6765798e6d001aa0dc95?event_id=5d9e67650050dc0e8d920000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-10-10 10:10
Duplicate of #1488

**Closed by norbertschuler** 2019-10-10 10:10 UTC
Labels: 1.1.0, bug, bugsnag, production
