### ISSUE TITLE
TypeError in node_modules/reactotron-react-native/node_modules/query-string/index.js:325

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2516] opened 2020-07-06 13:21 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **node_modules/reactotron-react-native/node_modules/query-string/index.js:325**
undefined is not an object (evaluating 't.selectedProject.paymentSetup.gateways[t.selectedProject.paymentSetup.defaultCountry].stripe')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f03256835c07000171a9fd8?event_id=5f032568005b8be4e7800000&i=gh&m=ci)

## Stacktrace

    node_modules/reactotron-react-native/node_modules/query-string/index.js:325 - c

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f03256835c07000171a9fd8?event_id=5f032568005b8be4e7800000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-07-06 13:26
Duplicate of #2473

**Closed by norbertschuler** 2020-07-06 13:26 UTC
Labels: 1.49.43, bug, bugsnag, testflight
