### ISSUE TITLE
RCTFatalException: unrecognized selector was thrown while invoking multiSet on target AsyncLocalStorage

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1746] opened 2019-12-13 07:13 UTC
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1d470b9a0' was thrown while invoking multiSet on target RNCAsyncStorage with params (         (                 (             AuthenticatedSideMenuSchema,             "<null>"         )     ),     108855 ) callstack: ( 	0   CoreFoundation                      0x0000000197739820 FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 1226784 	1   libobjc.A.dylib                     0x0000000197461fa4 objc_exception_throw +...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x1d470b9a0' was thrown while invoking multiSet on target RNCAsyncStorage with params (
        (
         ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df33a29c979230019b8c6c2?event_id=5df33a290054cf3a93fe0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df33a29c979230019b8c6c2?event_id=5df33a290054cf3a93fe0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:32
Duplicate of #1511

**Comment by norbertschuler** [comment] 2020-01-10 08:10
native error

**Closed by norbertschuler** 2020-01-10 08:10 UTC
Labels: 1.49.1, bug, bugsnag, production
