### ISSUE TITLE
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2034] opened 2020-03-09 14:51 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6657efed69950017eb41e3?event_id=5e6657ef00580b84d4270000&i=gh&m=ci)

## Stacktrace

    app/components/TreecounterGraphics/Trillion.native.js:241 - _renderScreen

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6657efed69950017eb41e3?event_id=5e6657ef00580b84d4270000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-02 05:55
Duplicate of #1861

**Closed by norbertschuler** 2020-04-02 05:55 UTC
Labels: 1.3.1, bug, bugsnag, production
