### ISSUE TITLE
My Trees - TPO link leads to wrong Destination

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2041] opened 2020-03-11 13:02 UTC
**In a user's profile: My Trees, it shows the Tree Planting Project for every donated / gifted /redeemed tree as a Link. This link does not lead to the Tree Planting project, though.**

The cause:
The link takes the Project ID and then uses it as a tree counter ID

For example:
Yucatán has Project ID: 1
So the Planted By Yucatán Link leads to:
Grace Kamau's Tree Counter - since it is tree counter 1
https://www.trilliontreecampaign.org/backend/treecounter/lookup/byTreecounter/1

For planted by Regenerating forests for Khasi communities (Project number 70)
https://www.trilliontreecampaign.org/backend/plantProject/70/show
It leads to:
https://www.trilliontreecampaign.org/backend/treecounter/lookup/byTreecounter/70

**The bug is on our current App-Version (production build).**

**To Reproduce**
Mobile App (not Web-App)
1. Go to Me
2. Click on one of your trees
3. Click on the "Planted By" TPO Name (Link)

For reference take a look at the picture below:

![bug-link-tpo-planted-by](https://user-images.githubusercontent.com/18365824/76418804-917c1700-639f-11ea-990a-4e8d284f1883.PNG)

**Comment by sagararyal** [comment] 2020-03-11 13:21
known issue will be fixed by 1.3.2

**Comment by norbertschuler** [comment] 2020-03-11 17:51
Duplicate of #1963

**Comment by harshvitra** [comment] 2020-03-12 19:30
Can we close this ?

**Closed** 2020-03-12 20:06 UTC
Labels: Android, bug, iOS
