### ISSUE TITLE
TypeError in /edit-profile

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2543] opened 2020-07-19 01:29 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/edit-profile**
Cannot read property 'first' of null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f13a203f1eb620017fda403?event_id=5f13a203005b8593a4480000&i=gh&m=ci)

## Stacktrace

    https://development.trilliontreecampaign.org/28.3d132fd3505bc5fc031c.js:1 - onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f13a203f1eb620017fda403?event_id=5f13a203005b8593a4480000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-07-19 01:31
Duplicate of #2524

**Closed by norbertschuler** 2020-07-19 01:31 UTC
Labels: 1.3.5, bug, bugsnag, production
