### ISSUE TITLE
java.lang.RuntimeException in Binder.java:763

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1590] opened 2019-11-03 19:09 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:763**
android.os.TransactionTooLargeException: data parcel size 581632 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbf25d8199f01001917f716?event_id=5dbf25d80052472f06270000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4156 - android.app.ActivityThread$StopInfo.run

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbf25d8199f01001917f716?event_id=5dbf25d80052472f06270000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:51
Duplicate of #1745

**Comment by Plant-for-the-Planet** [comment] 2020-01-21 15:57
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **Binder.java:763**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbf25d8199f01001917f716?event_id=5e271f6b0055e7f874390000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-01-21 16:05
native error

**Closed by norbertschuler** 2020-01-21 16:05 UTC
Labels: bug, bugsnag, production
