### ISSUE TITLE
Error in / - Request failed with status code 404

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2569] opened 2020-08-10 11:26 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 404

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f312ecec3bd56001857a5bd?event_id=5f312ece005b7bd7db590000&i=gh&m=ci)

## Stacktrace

    node_modules/metro/src/lib/polyfills/require.js:382 - parseHSL

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f312ecec3bd56001857a5bd?event_id=5f312ece005b7bd7db590000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-08-13 08:47
Duplicate of #2590

**Comment by Plant-for-the-Planet** [comment] 2020-08-24 11:53
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f312ecec3bd56001857a5bd?event_id=5f43aa3b005e088601820000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-09-17 14:41
Network errors should not be reported

**Closed by norbertschuler** 2020-09-17 14:41 UTC
Labels: 1.3.5, bug, bugsnag, production
