### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2335] opened 2020-05-10 07:42 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **Editor.java:6709**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7b06758037600176a646d?event_id=5eb7b067005b2ce6082d0000&i=gh&m=ci)

## Stacktrace

    Editor.java:6709 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7b06758037600176a646d?event_id=5eb7b067005b2ce6082d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 12:07
Duplicate of #2084

**Comment by Plant-for-the-Planet** [comment] 2020-07-09 19:58
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **Editor.java:6709**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7b06758037600176a646d?event_id=5f0776e6005b6c2a80dd0000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment] 2020-08-14 19:44
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **Editor.java:6709**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7b06758037600176a646d?event_id=5f36e995005b7088fa430000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-09-17 14:06
Duplicate of #2711

**Comment by Plant-for-the-Planet** [comment] 2020-10-16 16:16
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7b06758037600176a646d?event_id=5f89c76e006166ac0da50000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-12-18 08:13
Duplicate of #2711

**Closed by norbertschuler** 2020-12-18 08:13 UTC
Labels: 1.3.3, bug, bugsnag, native, production
