### ISSUE TITLE
Error in /pledge/mandoki-soulmates - pledgedEvent not in localStorage

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2198] opened 2020-04-10 14:30 UTC
## Error in Plant-for-the-Planet App

**Error** in **/pledge/mandoki-soulmates**
pledgedEvent not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9082f60e378a001785c5d6?event_id=5e9082f60059a4dc09360000&i=gh&m=ci)

## Stacktrace

    app/containers/Pledge/index.js:34 - PledgeContainer.componentDidMount

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9082f60e378a001785c5d6?event_id=5e9082f60059a4dc09360000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-10 15:06
Duplicate of #2012

**Closed by norbertschuler** 2020-04-10 15:06 UTC
Labels: 1.3.2, bug, bugsnag, production
