### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2711] opened 2020-09-06 22:44 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f55662cd19bf600177f0733?event_id=5f55662c005dfeba9f280000&i=gh&m=ci)

## Stacktrace

    Editor.java:6722 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f55662cd19bf600177f0733?event_id=5f55662c005dfeba9f280000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-10-03 08:05
Duplicate of #2710

**Comment by Plant-for-the-Planet** [comment] 2020-10-12 09:28
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f55662cd19bf600177f0733?event_id=5f8421a800616306b3760000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-12-18 08:13
Duplicate of #2711

**Closed by norbertschuler** 2020-12-18 08:13 UTC
Labels: 1.3.6, bug, bugsnag, native, production
