### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2789] opened 2020-10-10 13:15 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f81b3ea1350be001794d660?event_id=5f81b3ea0061534280160000&i=gh&m=ci)

## Stacktrace

    libpng.so:178000 - sub_filter_2bpp_neon64

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f81b3ea1350be001794d660?event_id=5f81b3ea0061534280160000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-10-10 13:47
Duplicate of #2788

**Closed by norbertschuler** 2020-10-10 13:47 UTC
Labels: 1.3.7, bug, bugsnag, production
