### ISSUE TITLE
TypeError in /gift-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#942] opened 2019-06-20 13:41 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
Cannot read property 'treecounter' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0b8ceb37d3590019b27376?event_id=5d0b8ceb00446a333c510000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/app/components/GiftTrees/index.js:184 - GiftTrees._this.checkValidation
    web/server/webpack:/app/components/GiftTrees/index.js:347 - validated
    web/server/webpack:/app/components/Common/Button/PrimaryButton.js:7 - PrimaryButton._react2.default.createElement.onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0b8ceb37d3590019b27376?event_id=5d0b8ceb00446a333c510000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-12 14:51
Duplicate of #1216

**Closed by norbertschuler** 2019-08-12 14:51 UTC
Labels: bug, bugsnag
