### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3024] opened 2021-05-18 08:54 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60a380dbfc3054000876c86c?event_id=60a380db007c8ca2a9ab0000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3994184 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60a380dbfc3054000876c86c?event_id=60a380db007c8ca2a9ab0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-05-21 08:33
Duplicate of #3027

**Closed by norbertschuler** 2021-05-21 08:33 UTC
Labels: 1.4.0, bug, bugsnag, production
