### ISSUE TITLE
java.lang.RuntimeException in Class.java:2327

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1649] opened 2019-11-21 00:22 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Class.java:2327**
Unable to start activity ComponentInfo{org.pftp/org.pftp.MainActivity}: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.inprogress.reactnativeyoutube.VideoFragment: could not find Fragment constructor

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dd5d8df13a3b0001acc65b4?event_id=5dd5d8df00532193b3830000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:2952 - android.app.ActivityThread.performLaunchActivity

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dd5d8df13a3b0001acc65b4?event_id=5dd5d8df00532193b3830000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-11-23 09:03
problem inside youtube npm module

**Comment by norbertschuler** [comment] 2019-12-13 07:49
Duplicate of #1742

**Closed by norbertschuler** 2019-12-13 07:49 UTC
Labels: 1.1.1, bug, bugsnag, production
