### ISSUE TITLE
Delete button can't be clicked

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1310] opened 2019-08-26 16:29 UTC
My Trees Section -> Mobile App (tested on Android)

Delete button can't be clicked.

I believe the changes to Single Contribution page is affecting this.

v.1.0.6.700013

**Comment by hkurra** [comment] 2019-08-27 18:28
@sagararyal this is android only? because not able to replicate on iOS

**Comment by sagararyal** [comment] 2019-08-27 19:08
Seems so, works on iOS

**Comment by norbertschuler** [comment] 2019-08-28 08:15
I can reproduce it on Android. Clicks on "Delete" (German "Löschen") does not do anything here:

![Screenshot_1566980095](https://user-images.githubusercontent.com/1532418/63837923-b0bfd380-c97c-11e9-8251-ef96513d9215.png)

**Comment by hkurra** [comment] 2019-08-30 10:09
Yes, working on it but as of now did not find any solution actually its a bug on android with react native if we have 2 touchable Feedback as parent-child,

**Comment by sagararyal** [comment] 2019-09-03 09:35
@hkurra any updates? we've had several complaints from users already.

**Comment by sagararyal** [comment] 2019-09-03 09:38
@hkurra any updates on this? we've received emails from several users already.

**Comment by norbertschuler** [comment] 2019-09-30 16:29
Obviously @hkurra wanted to say this issue got resolved within the PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1460

**Comment by norbertschuler** [comment] 2019-10-09 12:01
This is still an issue and we do not know if https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1460 will ever get merged:
![Screenshot_1570622452](https://user-images.githubusercontent.com/1532418/66479623-361ac580-ea9d-11e9-806d-12beb2126101.png)

**Closed** 2019-10-11 15:36 UTC
Labels: Android, P1, bug
