### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2705] opened 2020-09-02 05:57 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4f344d9261bf0017c8eaa5?event_id=5f4f344d005e0b153a240000&i=gh&m=ci)

## Stacktrace

    Editor.java:6700 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4f344d9261bf0017c8eaa5?event_id=5f4f344d005e0b153a240000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-09-17 14:06
Duplicate of #2711

**Comment by Plant-for-the-Planet** [comment] 2020-11-02 12:59
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4f344d9261bf0017c8eaa5?event_id=5fa002a100622a7cd05d0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-12-18 08:13
Duplicate of #2711

**Closed by norbertschuler** 2020-12-18 08:13 UTC
Labels: 1.3.6, bug, bugsnag, native, production
