### ISSUE TITLE
RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1f325fe28' was thrown while invoking multiSet on target RNCAsyncStorage with params (         (                 (             AuthenticatedSideMenuSchema,             "<null>"         )     ),     66821 ) callstack: ( 	0   CoreFoundation                      0x00000001b5b2dc44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516 	1   libobjc.A.dylib                     0x00000001b58480c8 objc_exception_throw + ... in facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1729] opened 2019-12-11 12:02 UTC
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1f325fe28' was thrown while invoking multiSet on target RNCAsyncStorage with params (         (                 (             AuthenticatedSideMenuSchema,             "<null>"         )     ),     66821 ) callstack: ( 	0   CoreFoundation                      0x00000001b5b2dc44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516 	1   libobjc.A.dylib                     0x00000001b58480c8 objc_exception_throw + ...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x1f325fe28' was thrown while invoking multiSet on target RNCAsyncStorage with params (
        (
         ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df0dacb530e6800191f789b?event_id=5df0dacb005466ef9d4f0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df0dacb530e6800191f789b?event_id=5df0dacb005466ef9d4f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-11 12:28
Duplicate of #1511

**Closed by norbertschuler** 2019-12-11 12:28 UTC
Labels: 1.49.1, bug, bugsnag, production
