### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2974] opened 2021-03-16 11:45 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60509a55f475670008c427df?event_id=60509a550073ad6cb6d40000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3803392 - 0x7510ae0900

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60509a55f475670008c427df?event_id=60509a550073ad6cb6d40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:35
Duplicate of #2982

**Comment by Plant-for-the-Planet** [comment] 2021-07-14 06:55
An error linked to this issue has been reopened in Bugsnag
[**SIGSEGV** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60509a55f475670008c427df?event_id=60ee8a68007f8d5b79ee0000&i=gh&m=ra)

**Closed** 2021-08-06 10:26 UTC
Labels: bug, bugsnag, production, 1.4.0
