### ISSUE TITLE
java.lang.NullPointerException in Editor.java:6705

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2084] opened 2020-03-29 15:31 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **Editor.java:6705**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e80bf6e7d3e150017ae5d44?event_id=5e80bf6e00594d6fa3350000&i=gh&m=ci)

## Stacktrace

```java
java.lang.NullPointerException Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference 
    Editor.java:6705 android.widget.Editor$SelectionModifierCursorController.access$300
    Editor.java:1470 android.widget.Editor.getEmailPopupWindow
    Editor.java:1478 android.widget.Editor.showEmailPopupWindow
    Editor.java:1457 android.widget.Editor.handleEmailPopup
    Editor.java:2100 android.widget.Editor.updateCursorPosition
    TextView.java:7823 android.widget.TextView.getUpdatedHighlightPath
    TextView.java:8008 android.widget.TextView.onDraw
    View.java:21472 android.view.View.draw
    View.java:20349 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4396 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4369 android.view.ViewGroup.dispatchGetDisplayList
    View.java:20309 android.view.View.updateDisplayListIfDirty
    ThreadedRenderer.java:575 android.view.ThreadedRenderer.updateViewTreeDisplayList
    ThreadedRenderer.java:581 android.view.ThreadedRenderer.updateRootDisplayList
    ThreadedRenderer.java:654 android.view.ThreadedRenderer.draw
    ViewRootImpl.java:3689 android.view.ViewRootImpl.draw
    ViewRootImpl.java:3484 android.view.ViewRootImpl.performDraw
    ViewRootImpl.java:2821 android.view.ViewRootImpl.performTraversals
    ViewRootImpl.java:1784 android.view.ViewRootImpl.doTraversal
    ViewRootImpl.java:7787 android.view.ViewRootImpl$TraversalRunnable.run
    Choreographer.java:1031 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:854 android.view.Choreographer.doCallbacks
    Choreographer.java:789 android.view.Choreographer.doFrame
    Choreographer.java:1016 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:883 android.os.Handler.handleCallback
    Handler.java:100 android.os.Handler.dispatchMessage
    Looper.java:224 android.os.Looper.loop
    ActivityThread.java:7520 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:539 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:950 com.android.internal.os.ZygoteInit.main

```
[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e80bf6e7d3e150017ae5d44?event_id=5e80bf6e00594d6fa3350000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-05-03 11:25
do not fix native bugs yet

**Comment by Plant-for-the-Planet** [comment] 2020-05-09 19:46
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **Editor.java:6705**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e80bf6e7d3e150017ae5d44?event_id=5eb70883005b382fded70000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-06-02 11:08
Related or duplicate of #2335

**Comment by norbertschuler** [comment] 2020-08-24 07:27
Duplicate of #2335

**Closed by norbertschuler** 2020-08-24 07:27 UTC
Labels: 1.3.1, bug, bugsnag, native, production

**Comment by vanzar-codigo** [comment] 2022-06-08 10:52
**editText.inputType = InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS** can solve this problem!!
The problem here is  miui framework auto suggest for email input field and then lead to crash....
Dont ever use **TYPE_TEXT_VARIATION_EMAIL_ADDRESS** and **TYPE_CLASS_TEXT**

**Comment by norbertschuler** [comment] 2022-06-08 19:06
> **editText.inputType = InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS** can solve this problem!! The problem here is miui framework auto suggest for email input field and then lead to crash.... Dont ever use **TYPE_TEXT_VARIATION_EMAIL_ADDRESS** and **TYPE_CLASS_TEXT**

Thank you for the hint. But as this project is build upon React-Native we cannot change out native Java code, but have to see if updates from the node modules will (or already have) solve(d) this problem.
