### ISSUE TITLE
Problem with Register Tree

### ISSUE THREAD

**Issue by Chiagozie-Udeh** [Plant-for-the-Planet-org/treecounter-app#2561] opened 2020-08-03 16:35 UTC
**Register Tree is Not Working**
*The final button, after adding the picture of the tree and writing the tree name, it doesn't work. You click and nothing happens.*

**Production**

**To Reproduce**
1. Go to 'Me'
2. Click on 'Register Tree'
3. Scroll down to 'Add a Tree'

**Expected behavior**
*When you click "Add a Tree", it loads another page where you complete the submission.*

**What actually happens**
*Nothing at all, it remains inactive.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (Asus)
- OS
- Chrome
- Plant-for-the-Planet Client Version [e.g. 1.3.4]

**Smartphone (please complete the following information):**
- Device: Samsung A70
- OS: [e.g. iOS 13.5]
- Chrome
- Plant-for-the-Planet App Version [e.g. 1.3.4]

**Additional context**
Same problem on all devices both for Single and Multiple tree registration

**Comment by norbertschuler** [comment] 2020-08-04 04:05
Duplicate of #2555

**Closed by norbertschuler** 2020-08-04 04:05 UTC
Labels: bug
