### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2960] opened 2021-03-02 18:06 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/603e7e93590091001700d810?event_id=603e7e930072e3907b500000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3839580 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/603e7e93590091001700d810?event_id=603e7e930072e3907b500000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:33
Duplicate of #2979

**Closed by norbertschuler** 2021-03-29 07:33 UTC
Labels: 1.4.0, bug, bugsnag, production
