### ISSUE TITLE
YouTubePlayer has been released

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1488] opened 2019-09-28 20:59 UTC
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MainActivity**
This YouTubePlayer has been released

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8fc9b6d4d50f001a4ec832?event_id=5d8fc9b60050379680e70000&i=gh&m=ci)

## Stacktrace

    SourceFile:70 - ndb.aa

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8fc9b6d4d50f001a4ec832?event_id=5d8fc9b60050379680e70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-11-23 09:01
Duplicate of #1655

**Closed by norbertschuler** 2019-11-23 09:01 UTC
Labels: 1.1.0, bug, bugsnag, production
