### ISSUE TITLE
TypeError in app/components/DonateTrees/index.native.js:395 - null is not an object (evaluating 'this.props.selectedProject.id')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2246] opened 2020-04-26 09:13 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/DonateTrees/index.native.js:395**
null is not an object (evaluating 'this.props.selectedProject.id')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea550a169a03300173ef828?event_id=5ea550a1005ab3cdc0500000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/index.native.js:395 - value
    app/components/DonateTrees/index.native.js:197 - value
    app/components/DonateTrees/index.native.js:141 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea550a169a03300173ef828?event_id=5ea550a1005ab3cdc0500000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-06-22 11:58
Should hopefully get fixed with #1908

**Comment by norbertschuler** [comment] 2020-09-17 14:51
Duplicate of #2720

**Closed by norbertschuler** 2020-09-17 14:51 UTC
Labels: 1.49.41, bug, bugsnag, production
