### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2533] opened 2020-07-16 14:18 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **Editor.java:6726**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f106197f73f7e00175c68f6?event_id=5f106197005b6bcc8afd0000&i=gh&m=ci)

## Stacktrace

    Editor.java:6726 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f106197f73f7e00175c68f6?event_id=5f106197005b6bcc8afd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-07-17 09:24
Duplicate of #2084

**Comment by Plant-for-the-Planet** [comment] 2020-09-24 20:34
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f106197f73f7e00175c68f6?event_id=5f6d02e3005defc29eff0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-10-03 10:03
Duplicate of #2741

**Comment by Plant-for-the-Planet** [comment] 2020-10-17 21:18
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f106197f73f7e00175c68f6?event_id=5f8b5fb800615d4874fe0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-12-18 08:13
Duplicate of #2711

**Closed by norbertschuler** 2020-12-18 08:13 UTC
Labels: 1.3.4, bug, bugsnag, native, production
