### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2792] opened 2020-10-11 21:30 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f83795c3199f2001836fd5a?event_id=5f83795c0061584fdcf50000&i=gh&m=ci)

## Stacktrace

    Editor.java:6705 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f83795c3199f2001836fd5a?event_id=5f83795c0061584fdcf50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-12-18 08:12
Duplicate of #2711

**Closed by norbertschuler** 2020-12-18 08:12 UTC
Labels: 1.3.7, bug, bugsnag, native, production
