### ISSUE TITLE
java.lang.RuntimeException in Binder.java:1145

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1602] opened 2019-11-07 13:43 UTC
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **Binder.java:1145**
android.os.TransactionTooLargeException: data parcel size 625988 bytes

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc41f8130dd620019716a7f?event_id=5dc41f810052c51239310000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:4528 - android.app.ActivityThread.handleSleeping

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc41f8130dd620019716a7f?event_id=5dc41f810052c51239310000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-12-13 07:50
Duplicate of #1745

**Comment by Plant-for-the-Planet** [comment] 2019-12-22 19:11
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **Binder.java:1145**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc41f8130dd620019716a7f?event_id=5dffbfe70054ca85fddc0000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-01-10 08:12
native error

**Closed by norbertschuler** 2020-01-10 08:12 UTC
Labels: 1.1.1, bug, bugsnag, production
