### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2951] opened 2021-02-20 05:56 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6030a4947338840018446b27?event_id=6030a494006cc3cf8f4c0000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3798592 - 0x782c137640

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6030a4947338840018446b27?event_id=6030a494006cc3cf8f4c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:35
Duplicate of #2982

**Closed by norbertschuler** 2021-03-29 07:35 UTC
Labels: 1.3.9, bug, bugsnag, production
