### ISSUE TITLE
Plant for the planet app issue

### ISSUE THREAD

**Issue by csababablena** [Plant-for-the-Planet-org/treecounter-app#2790] opened 2020-10-11 08:42 UTC
When I click donate in the app nothing happens!

**Comment by norbertschuler** [comment] 2020-10-11 08:46
@csababablena can you please try to add some details, e.g. which type of phone you are using and share a screenshot of the donate button or screen where the donation does not work?

**Comment by csababablena** [comment] 2020-10-11 08:50
Hello

I'm using Samsung galaxy s10

See screenshot attached where "next" button doesn't work

Do you need any other information?

Thanks

**Comment by norbertschuler** [comment] 2020-10-11 09:05
> Hello I'm using Samsung galaxy s10 See screenshot attached where "next" button doesn't work Do you need any other information? Thanks

I am afraid I cannot see any screen shot in this GitHub issue using the browser to view it. Maybe you added an attachment to your answering mail, but the screen get not uploaded to GitHub. 

I just saw your mail to have sent to our support describing your problem not being able to pass the screen where you have to enter your address details. From that information I assume you currently face our latest bug not being able to donate an amount less then 1€ which unfortunately results into not being able to go "next" after filling the address data and not getting any correct error message about that. If you don't mind, please try to raise your donation amount and test if you can pass the address screen and continue with entering the payment data in the browser opened by the app (due to the rules of the App stores we are not allowed to do the payment within the app). No worries, you can stop the donation process at that time, just closing the browser if you do not want to donate a higher amount.

**Comment by csababablena** [comment] 2020-10-11 09:07
Hello

I am trying to donate €200

I will try to upload the photo on github again

Thanks

**Comment by csababablena** [comment] 2020-10-11 09:10
![Screenshot_20201011-100959_Plant](https://user-images.githubusercontent.com/72687391/95674714-f0aa4000-0ba9-11eb-89ab-807816262c1b.jpg)

**Comment by csababablena** [comment] 2020-10-11 09:19
It worked for a different provider!
For the following provider the issue still exists:

![Uploading Screenshot_20201011-101653_Plant.jpg…]()

**Comment by csababablena** [comment] 2020-10-11 09:19
![Uploading Screenshot_20201011-101653_Plant.jpg…]()

**Comment by norbertschuler** [comment] 2020-10-11 09:20
Sorry, the screen shots are broken. What _provider_ do you mean?

**Comment by csababablena** [comment] 2020-10-11 09:26
See 2 providers below

Tree planting for biodiversity conservation - working fine, I was able to
click next and donate

Kasungu indigenous reforestation project - issue still exists, next button
doesn't work

**Comment by norbertschuler** [comment] 2020-10-11 09:48
> See 2 providers below
>
> Tree planting for biodiversity conservation - working fine, I was able to click next and donate
>
> Kasungu indigenous reforestation project - issue still exists, next button doesn't work

I am sorry, I cannot reproduce the error on my device. I can donate on both projects. Maybe if you wish to donate for the second project, you can just use our new website at https://beta.plant-for-the-planet.org/?p=chitipa-planting-trees-project-gps-validated

**Comment by csababablena** [comment] 2020-10-11 09:53
Ok thank you
The website works fine

Probably just an issue with the app

**Closed** 2021-05-06 10:36 UTC
Labels: Android, bug
