### ISSUE TITLE
TypeError in /leaderboard/country - undefined is not an object (evaluating 't.options[t.selectedIndex].value')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2208] opened 2020-04-17 14:11 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/leaderboard/country**
undefined is not an object (evaluating 't.options[t.selectedIndex].value')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e99b90505352200176f2867?event_id=5e99b9050059e9a441190000&i=gh&m=ci)

## Stacktrace

    app/components/Leaderboard/index.js:29 - 
    app/components/Leaderboard/index.js:24 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e99b90505352200176f2867?event_id=5e99b9050059e9a441190000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-04-17 14:26
Probably `this.refs.orderBy` is not always defined. This happened on iOS.

**Comment by norbertschuler** [comment] 2020-09-17 14:49
Duplicate of #2574

**Closed by norbertschuler** 2020-09-17 14:49 UTC
Labels: 1.3.2, bug, bugsnag, production
