### ISSUE TITLE
RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1f233f9a0' was thrown while invoking multiSet on target AsyncLocalStorage with params (         (                 (             AuthenticatedSideMenuSchema,             "<null>"         )     ),     119827 ) callstack: ( 	0   CoreFoundation                      0x00000001b61ec9a0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227168 	1   libobjc.A.dylib                     0x00000001b5f150a4 objc_exception_throw... in facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1585] opened 2019-11-01 12:25 UTC
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1f233f9a0' was thrown while invoking multiSet on target AsyncLocalStorage with params (         (                 (             AuthenticatedSideMenuSchema,             "<null>"         )     ),     119827 ) callstack: ( 	0   CoreFoundation                      0x00000001b61ec9a0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227168 	1   libobjc.A.dylib                     0x00000001b5f150a4 objc_exception_throw...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x1f233f9a0' was thrown while invoking multiSet on target AsyncLocalStorage with params (
        (
       ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbc2435037925001baab75f?event_id=5dbc243500523a5891390000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbc2435037925001baab75f?event_id=5dbc243500523a5891390000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-11-01 12:56
Duplicate of #1511

**Closed by norbertschuler** 2019-11-01 12:56 UTC
Labels: 1.49, bug, bugsnag, production
