### ISSUE TITLE
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2757] opened 2020-10-01 19:05 UTC
## Error in Plant-for-the-Planet App

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f762874c5e35a00179ed4de?event_id=5f7628740060cb7681410000&i=gh&m=ci)

## Stacktrace

    Editor.java:6710 - android.widget.Editor$SelectionModifierCursorController.access$300

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f762874c5e35a00179ed4de?event_id=5f7628740060cb7681410000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment] 2020-10-03 09:49
https://github.com/facebook/react-native/issues/27204

Comment added in Bugsnag by Norbert Schuler
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f762874c5e35a00179ed4de?event_id=5f7628740060cb7681410000&i=gh&m=cm)

**Comment by norbertschuler** [comment] 2020-10-03 09:59
Duplicate of #2741

**Comment by Plant-for-the-Planet** [comment] 2020-10-16 05:36
An error linked to this issue has been reopened in Bugsnag
[**java.lang.NullPointerException** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f762874c5e35a00179ed4de?event_id=5f89316d006169670bd80000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2020-12-18 08:12
Duplicate of #2711

**Closed by norbertschuler** 2020-12-18 08:12 UTC
Labels: 1.3.6, bug, bugsnag, native, production
