### ISSUE TITLE
Error in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1325] opened 2019-08-28 12:22 UTC
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 401

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6671ebf88d8f0019e66f03?event_id=5d6671eb004e3cf3c20b0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:37567 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6671ebf88d8f0019e66f03?event_id=5d6671eb004e3cf3c20b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-28 14:56
Duplicate of #1328

**Closed by norbertschuler** 2019-08-28 14:56 UTC
Labels: 1.0.6, bug, bugsnag, production
