### ISSUE TITLE
TypeError in /gift-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1006] opened 2019-07-01 03:58 UTC
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
Cannot read property 'treecounter' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d08a41fb799df00182a72b3?event_id=5d1953780045eb1cb6220000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/app/components/GiftTrees/index.js:184 - GiftTrees.t.checkValidation
    web/server/webpack:/app/components/GiftTrees/index.js:347 - validated
    web/server/webpack:/app/components/Common/Button/PrimaryButton.js:7 - a.default.createElement.onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d08a41fb799df00182a72b3?event_id=5d1953780045eb1cb6220000&i=gh&m=ci)

*Created by Norbert Schuler via Bugsnag*

**Comment by norbertschuler** [comment] 2019-08-12 09:36
This happens when you just press "next" without selection an existing user.

**Comment by norbertschuler** [comment] 2019-08-12 09:37
Duplicate of #1216

**Comment by Plant-for-the-Planet** [comment] 2019-08-13 22:05
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/gift-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d08a41fb799df00182a72b3?event_id=5d53342a004cd8649fd40000&i=gh&m=ra)

**Closed** 2019-09-18 08:34 UTC
Labels: bug, bugsnag
