### ISSUE TITLE
SIGSEGV in MainActivity - system/lib64/libhwui.so:3862452 - SkSurface::getCanvas()

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3007] opened 2021-04-26 10:47 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60869a5c337fc000074880b8?event_id=60869a5c00781670f5010000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3862452 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60869a5c337fc000074880b8?event_id=60869a5c00781670f5010000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-05-21 08:34
Duplicate of #3027

**Comment by Plant-for-the-Planet** [comment] 2021-06-30 12:02
An error linked to this issue has been reopened in Bugsnag
[**SIGSEGV** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/60869a5c337fc000074880b8?event_id=60dc5d5c007f63ee25770000&i=gh&m=ra)

**Closed** 2021-08-06 10:26 UTC
Labels: bug, bugsnag, production, 1.4.0
