### ISSUE TITLE
SIGSEGV in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2941] opened 2021-02-01 06:52 UTC
## Error in Plant-for-the-Planet App

**SIGSEGV** in **MainActivity**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6017a52ce42f96001743206e?event_id=6017a52c006994ba9d5a0000&i=gh&m=ci)

## Stacktrace

    /system/lib64/libhwui.so:3864900 - SkSurface::getCanvas()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6017a52ce42f96001743206e?event_id=6017a52c006994ba9d5a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-03-29 07:33
Duplicate of #2979

**Closed by norbertschuler** 2021-03-29 07:33 UTC
Labels: 1.3.9, bug, bugsnag, production
