### ISSUE TITLE
Error in /pledge/klima-check-up-lippe

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2028] opened 2020-03-05 11:00 UTC
## Error in Plant-for-the-Planet App

**Error** in **/pledge/klima-check-up-lippe**
pledgedEvent not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e60dbe02bd4f800178026e8?event_id=5e60dbe00058448278280000&i=gh&m=ci)

## Stacktrace

    app/stores/localStorage.js:34 - 
    app/stores/localStorage.js:31 - fetchItem
    app/containers/Pledge/index.js:55 - PledgeContainer.componentDidUpdate

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e60dbe02bd4f800178026e8?event_id=5e60dbe00058448278280000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2020-03-06 15:28
This happened on 	
https://www.weplant.app/pledge/klima-check-up-lippe

**Comment by norbertschuler** [comment] 2020-03-07 09:54
<img width="1667" alt="Bildschirmfoto 2020-03-07 um 10 54 17" src="https://user-images.githubusercontent.com/1532418/76141176-04188a00-6062-11ea-8604-bd80c1f53882.png">

https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/timeline?filters[event.since][0]=2020-03-06T06%3A03%3A32.186Z&filters[error.status][0]=open&filters[event.before][0]=2020-03-06T20%3A36%3A48.212Z&pivot_tab=error&sort=events

**Comment by norbertschuler** [comment] 2020-04-02 05:49
Duplicate of #2012

**Closed by norbertschuler** 2020-04-02 05:49 UTC
Labels: 1.3.1, bug, bugsnag, production
